// Copyright (c) 2026, mkgui contributors
// SPDX-License-Identifier: MIT
// Generated by mkgui-editor -- do not edit by hand

#include "mkgui.c"

// ---------------------------------------------------------------------------
// Editor constants
// ---------------------------------------------------------------------------

#define ED_MAX_WIDGETS    512
#define ED_MAX_UNDO       64
#define ED_GRID_DEFAULT   8
#define ED_CANVAS_DEF_W   640
#define ED_CANVAS_DEF_H   480
#define ED_LEFT_W         200
#define ED_RIGHT_W        320
#define ED_PAL_ROWS       ((ED_WIDGET_COUNT + 1) / 2)
#define ED_PALETTE_H      (36 + ED_PAL_ROWS * 22 + (ED_PAL_ROWS - 1) * MKGUI_BOX_GAP)
#define ED_CTN_ROWS       ((ED_CONTAINER_COUNT + 1) / 2)
#define ED_CTN_H          (36 + ED_CTN_ROWS * 22 + (ED_CTN_ROWS - 1) * MKGUI_BOX_GAP)
#define ED_TOP_H          (MKGUI_MENU_HEIGHT + MKGUI_TOOLBAR_HEIGHT)
#define ED_BOT_H          MKGUI_STATUSBAR_HEIGHT

// ---------------------------------------------------------------------------
// Editor widget IDs
// ---------------------------------------------------------------------------

enum {
	ED_WINDOW = 0,
	ED_MENU, ED_FILE_MENU, ED_EDIT_MENU,
	ED_MI_NEW, ED_MI_OPEN, ED_MI_SAVE, ED_MI_SAVEAS, ED_MI_GENERATE, ED_MI_EXIT,
	ED_MI_UNDO, ED_MI_REDO, ED_MI_COPY, ED_MI_PASTE, ED_MI_DELETE,
	ED_TOOLBAR = 20,
	ED_TB_NEW, ED_TB_OPEN, ED_TB_SAVE, ED_TB_GEN, ED_TB_TEST,
	ED_TB_UNDO, ED_TB_REDO,
	ED_SPLIT_MAIN = 30,
	ED_SPLIT_RIGHT = 31,
	ED_TREE = 32,
	ED_CANVAS_LBL = 33,
	ED_RIGHT_PANEL = 34,
	ED_PAL_GROUP = 40,
	ED_PAL_FIRST = 41,
	ED_PAL_HBOX = 70,
	ED_PAL_COL0 = 71,
	ED_PAL_COL1 = 72,
	ED_CTN_GROUP = 73,
	ED_CTN_HBOX = 74,
	ED_CTN_COL0 = 75,
	ED_CTN_COL1 = 76,
	ED_CTN_FIRST = 200,
	ED_PROP_GROUP = 80,
	ED_PROP_TYPE_LBL = 81, ED_PROP_TYPE_VAL,
	ED_PROP_ID_LBL, ED_PROP_ID_INP,
	ED_PROP_LABEL_LBL, ED_PROP_LABEL_INP,
	ED_PROP_ICON_LBL, ED_PROP_ICON_INP,
	ED_PROP_PARENT_LBL, ED_PROP_PARENT_DRP,
	ED_PROP_X_LBL, ED_PROP_X_SPN,
	ED_PROP_Y_LBL, ED_PROP_Y_SPN,
	ED_PROP_W_LBL, ED_PROP_W_SPN,
	ED_PROP_H_LBL, ED_PROP_H_SPN,
	ED_PROP_TAB_LBL, ED_PROP_TAB_SPN,
	ED_PROP_FLAGS_LBL,
	ED_PROP_FL_LEFT, ED_PROP_FL_TOP, ED_PROP_FL_RIGHT, ED_PROP_FL_BOTTOM,
	ED_PROP_FL_VIRTUAL, ED_PROP_FL_HIDDEN, ED_PROP_FL_DISABLED,
	ED_PROP_FL_CHECKED, ED_PROP_FL_SEPARATOR,
	ED_PROP_FL_MENUCHECK, ED_PROP_FL_MENURADIO,
	ED_PROP_FL_REGTOP, ED_PROP_FL_REGBOT, ED_PROP_FL_REGLEFT, ED_PROP_FL_REGRIGHT,
	ED_PROP_ICON_BROWSE,
	ED_PROP_ADD_TAB, ED_PROP_REM_TAB,
	ED_PROP_ADD_ITEM, ED_PROP_REM_ITEM,
	ED_MENU_TREE,
	ED_PROP_VBOX = 130,
	ED_PROP_FORM,
	ED_PROP_ICON_HBOX,
	ED_PROP_POS_HBOX,
	ED_PROP_SIZE_HBOX,
	ED_PROP_FL_HBOX,
	ED_PROP_FL_COL0,
	ED_PROP_FL_COL1,
	ED_PROP_FL_COL2,
	ED_PROP_FL_COL3,
	ED_PROP_BTN_HBOX,
	ED_STATUSBAR = 170,
};

// ---------------------------------------------------------------------------
// Palette entries
// ---------------------------------------------------------------------------

struct ed_palette_entry {
	const char *name;
	uint32_t type;
};

static struct ed_palette_entry ed_widgets[] = {
	{ "Button",     MKGUI_BUTTON },
	{ "Checkbox",   MKGUI_CHECKBOX },
	{ "Dropdown",   MKGUI_DROPDOWN },
	{ "GLView",     MKGUI_GLVIEW },
	{ "Image",      MKGUI_IMAGE },
	{ "Input",      MKGUI_INPUT },
	{ "ItemView",   MKGUI_ITEMVIEW },
	{ "Label",      MKGUI_LABEL },
	{ "Listview",   MKGUI_LISTVIEW },
	{ "Progress",   MKGUI_PROGRESS },
	{ "Radio",      MKGUI_RADIO },
	{ "Scrollbar",  MKGUI_SCROLLBAR },
	{ "Slider",     MKGUI_SLIDER },
	{ "Spinbox",    MKGUI_SPINBOX },
	{ "Spinner",    MKGUI_SPINNER },
	{ "Statusbar",  MKGUI_STATUSBAR },
	{ "Textarea",   MKGUI_TEXTAREA },
	{ "Treeview",   MKGUI_TREEVIEW },
};

static struct ed_palette_entry ed_containers[] = {
	{ "Form",       MKGUI_FORM },
	{ "Group",      MKGUI_GROUP },
	{ "HBox",       MKGUI_HBOX },
	{ "VBox",       MKGUI_VBOX },
	{ "HSplit",     MKGUI_HSPLIT },
	{ "VSplit",     MKGUI_VSPLIT },
	{ "Menu",       MKGUI_MENU },
	{ "Panel",      MKGUI_PANEL },
	{ "Tabs",       MKGUI_TABS },
	{ "Toolbar",    MKGUI_TOOLBAR },
};

#define ED_WIDGET_COUNT    (sizeof(ed_widgets) / sizeof(ed_widgets[0]))
#define ED_CONTAINER_COUNT (sizeof(ed_containers) / sizeof(ed_containers[0]))

// ---------------------------------------------------------------------------
// Type name lookup
// ---------------------------------------------------------------------------

// [=]===^=[ ed_type_name ]=======================================[=]
static const char *ed_type_name(uint32_t type) {
	for(uint32_t i = 0; i < ED_WIDGET_COUNT; ++i) {
		if(ed_widgets[i].type == type) {
			return ed_widgets[i].name;
		}
	}
	for(uint32_t i = 0; i < ED_CONTAINER_COUNT; ++i) {
		if(ed_containers[i].type == type) {
			return ed_containers[i].name;
		}
	}
	if(type == MKGUI_TAB) { return "Tab"; }
	if(type == MKGUI_MENUITEM) { return "MenuItem"; }
	return "Unknown";
}

// ---------------------------------------------------------------------------
// Editor widget (designed widget)
// ---------------------------------------------------------------------------

struct ed_widget {
	uint32_t type;
	uint32_t id;
	char id_name[64];
	char label[MKGUI_MAX_TEXT];
	char icon[MKGUI_ICON_NAME_LEN];
	uint32_t parent_id;
	int32_t x, y, w, h;
	uint32_t flags;
	uint32_t tab_order;
};

// ---------------------------------------------------------------------------
// Undo snapshot
// ---------------------------------------------------------------------------

struct ed_snapshot {
	struct ed_widget widgets[ED_MAX_WIDGETS];
	uint32_t widget_count;
};

// ---------------------------------------------------------------------------
// Editor tab state (tracks active tab per Tabs widget)
// ---------------------------------------------------------------------------

struct ed_tab_state {
	uint32_t tabs_id;
	uint32_t active_id;
};

// ---------------------------------------------------------------------------
// Editor state
// ---------------------------------------------------------------------------

struct ed_state {
	struct ed_widget widgets[ED_MAX_WIDGETS];
	uint32_t widget_count;

	int32_t selected;
	uint32_t placement_type;
	uint32_t next_id;

	int32_t canvas_w, canvas_h;
	int32_t grid_size;

	int32_t drag_active;
	int32_t drag_ox, drag_oy;
	int32_t resize_handle;
	int32_t resize_start_x, resize_start_y, resize_start_w, resize_start_h;
	uint32_t canvas_resize_edge;

	struct ed_snapshot undo[ED_MAX_UNDO];
	uint32_t undo_pos;
	uint32_t undo_count;

	char project_path[512];

	struct ed_tab_state tab_states[32];
	uint32_t tab_state_count;
};

static struct ed_state ed;

// ---------------------------------------------------------------------------
// Tab state helpers
// ---------------------------------------------------------------------------

// [=]===^=[ ed_get_active_tab ]===================================[=]
static uint32_t ed_get_active_tab(uint32_t tabs_id) {
	for(uint32_t i = 0; i < ed.tab_state_count; ++i) {
		if(ed.tab_states[i].tabs_id == tabs_id) {
			return ed.tab_states[i].active_id;
		}
	}
	for(uint32_t i = 0; i < ed.widget_count; ++i) {
		if(ed.widgets[i].type == MKGUI_TAB && ed.widgets[i].parent_id == tabs_id) {
			return ed.widgets[i].id;
		}
	}
	return 0;
}

// [=]===^=[ ed_set_active_tab ]===================================[=]
static void ed_set_active_tab(uint32_t tabs_id, uint32_t tab_id) {
	for(uint32_t i = 0; i < ed.tab_state_count; ++i) {
		if(ed.tab_states[i].tabs_id == tabs_id) {
			ed.tab_states[i].active_id = tab_id;
			return;
		}
	}
	if(ed.tab_state_count < 32) {
		ed.tab_states[ed.tab_state_count].tabs_id = tabs_id;
		ed.tab_states[ed.tab_state_count].active_id = tab_id;
		++ed.tab_state_count;
	}
}

// [=]===^=[ ed_is_tab_child_visible ]=============================[=]
static uint32_t ed_is_tab_child_visible(uint32_t idx) {
	struct ed_widget *w = &ed.widgets[idx];
	for(uint32_t j = 0; j < ed.widget_count; ++j) {
		if(ed.widgets[j].id == w->parent_id && ed.widgets[j].type == MKGUI_TAB) {
			uint32_t tabs_id = ed.widgets[j].parent_id;
			if(ed_get_active_tab(tabs_id) != ed.widgets[j].id) {
				return 0;
			}
		}
	}
	return 1;
}

// ---------------------------------------------------------------------------
// Undo / redo
// ---------------------------------------------------------------------------

// [=]===^=[ ed_push_undo ]=======================================[=]
static void ed_push_undo(void) {
	struct ed_snapshot *snap = &ed.undo[ed.undo_pos % ED_MAX_UNDO];
	memcpy(snap->widgets, ed.widgets, sizeof(struct ed_widget) * ed.widget_count);
	snap->widget_count = ed.widget_count;
	++ed.undo_pos;
	ed.undo_count = ed.undo_pos;
}

// [=]===^=[ ed_undo ]============================================[=]
static void ed_undo(void) {
	if(ed.undo_pos == 0) {
		return;
	}
	--ed.undo_pos;
	struct ed_snapshot *snap = &ed.undo[ed.undo_pos % ED_MAX_UNDO];
	memcpy(ed.widgets, snap->widgets, sizeof(struct ed_widget) * snap->widget_count);
	ed.widget_count = snap->widget_count;
	ed.selected = -1;
}

// [=]===^=[ ed_redo ]============================================[=]
static void ed_redo(void) {
	if(ed.undo_pos >= ed.undo_count) {
		return;
	}
	++ed.undo_pos;
	if(ed.undo_pos < ed.undo_count) {
		struct ed_snapshot *snap = &ed.undo[ed.undo_pos % ED_MAX_UNDO];
		memcpy(ed.widgets, snap->widgets, sizeof(struct ed_widget) * snap->widget_count);
		ed.widget_count = snap->widget_count;
	}
	ed.selected = -1;
}

// ---------------------------------------------------------------------------
// Editor helpers
// ---------------------------------------------------------------------------

// [=]===^=[ ed_find_widget ]=====================================[=]
static int32_t ed_find_widget(uint32_t id) {
	for(uint32_t i = 0; i < ed.widget_count; ++i) {
		if(ed.widgets[i].id == id) {
			return (int32_t)i;
		}
	}
	return -1;
}

// [=]===^=[ ed_gen_id_name ]=====================================[=]
static void ed_gen_id_name(struct ed_widget *w) {
	const char *prefix = "ID";
	switch(w->type) {
		case MKGUI_WINDOW:     { prefix = "ID_WINDOW"; } break;
		case MKGUI_BUTTON:     { prefix = "ID_BUTTON"; } break;
		case MKGUI_LABEL:      { prefix = "ID_LABEL"; } break;
		case MKGUI_INPUT:      { prefix = "ID_INPUT"; } break;
		case MKGUI_CHECKBOX:   { prefix = "ID_CHECK"; } break;
		case MKGUI_DROPDOWN:   { prefix = "ID_DROPDOWN"; } break;
		case MKGUI_SLIDER:     { prefix = "ID_SLIDER"; } break;
		case MKGUI_LISTVIEW:   { prefix = "ID_LISTVIEW"; } break;
		case MKGUI_TABS:       { prefix = "ID_TABS"; } break;
		case MKGUI_TAB:        { prefix = "ID_TAB"; } break;
		case MKGUI_HSPLIT: { prefix = "ID_SPLITH"; } break;
		case MKGUI_VSPLIT: { prefix = "ID_SPLITV"; } break;
		case MKGUI_TREEVIEW:   { prefix = "ID_TREEVIEW"; } break;
		case MKGUI_MENU:       { prefix = "ID_MENU"; } break;
		case MKGUI_MENUITEM:   { prefix = "ID_MENUITEM"; } break;
		case MKGUI_STATUSBAR:  { prefix = "ID_STATUSBAR"; } break;
		case MKGUI_TOOLBAR:    { prefix = "ID_TOOLBAR"; } break;
		case MKGUI_RADIO:      { prefix = "ID_RADIO"; } break;
		case MKGUI_PROGRESS:   { prefix = "ID_PROGRESS"; } break;
		case MKGUI_TEXTAREA:   { prefix = "ID_TEXTAREA"; } break;
		case MKGUI_SPINBOX:    { prefix = "ID_SPINBOX"; } break;
		case MKGUI_GROUP:      { prefix = "ID_GROUP"; } break;
		case MKGUI_SPINNER:    { prefix = "ID_SPINNER"; } break;
		case MKGUI_ITEMVIEW:   { prefix = "ID_ITEMVIEW"; } break;
		case MKGUI_PANEL:      { prefix = "ID_PANEL"; } break;
		case MKGUI_SCROLLBAR:  { prefix = "ID_SCROLLBAR"; } break;
		case MKGUI_IMAGE:      { prefix = "ID_IMAGE"; } break;
		case MKGUI_GLVIEW:     { prefix = "ID_GLVIEW"; } break;
		case MKGUI_VBOX:       { prefix = "ID_VBOX"; } break;
		case MKGUI_HBOX:       { prefix = "ID_HBOX"; } break;
		case MKGUI_FORM:       { prefix = "ID_FORM"; } break;
		default: break;
	}
	snprintf(w->id_name, sizeof(w->id_name), "%s_%u", prefix, w->id);
}

// [=]===^=[ ed_add_widget ]======================================[=]
static int32_t ed_add_widget(uint32_t type, int32_t x, int32_t y) {
	if(ed.widget_count >= ED_MAX_WIDGETS) {
		return -1;
	}

	ed_push_undo();

	struct ed_widget *w = &ed.widgets[ed.widget_count];
	memset(w, 0, sizeof(*w));
	w->type = type;
	w->id = ed.next_id++;
	w->x = x;
	w->y = y;

	switch(type) {
		case MKGUI_WINDOW: {
			w->w = ED_CANVAS_DEF_W;
			w->h = ED_CANVAS_DEF_H;
			snprintf(w->label, sizeof(w->label), "Window");
		} break;

		case MKGUI_BUTTON: {
			w->w = 80;
			w->h = 28;
			snprintf(w->label, sizeof(w->label), "Button");
		} break;

		case MKGUI_LABEL: {
			w->w = 80;
			w->h = 20;
			snprintf(w->label, sizeof(w->label), "Label");
		} break;

		case MKGUI_INPUT: {
			w->w = 150;
			w->h = 24;
		} break;

		case MKGUI_CHECKBOX: {
			w->w = 120;
			w->h = 20;
			snprintf(w->label, sizeof(w->label), "Checkbox");
		} break;

		case MKGUI_DROPDOWN: {
			w->w = 150;
			w->h = 24;
		} break;

		case MKGUI_SLIDER: {
			w->w = 200;
			w->h = 20;
			snprintf(w->label, sizeof(w->label), "Slider");
		} break;

		case MKGUI_LISTVIEW: {
			w->w = 300;
			w->h = 200;
		} break;

		case MKGUI_TABS: {
			w->w = 300;
			w->h = 200;
		} break;

		case MKGUI_TAB: {
			w->w = 0;
			w->h = 0;
			snprintf(w->label, sizeof(w->label), "Tab");
		} break;

		case MKGUI_HSPLIT:
		case MKGUI_VSPLIT: {
			w->w = 300;
			w->h = 200;
		} break;

		case MKGUI_TREEVIEW: {
			w->w = 200;
			w->h = 200;
		} break;

		case MKGUI_MENU: {
			w->x = 0;
			w->y = 0;
			w->w = ed.canvas_w;
			w->h = MKGUI_MENU_HEIGHT;
			w->flags = MKGUI_ANCHOR_LEFT | MKGUI_ANCHOR_TOP | MKGUI_ANCHOR_RIGHT;
		} break;

		case MKGUI_MENUITEM: {
			snprintf(w->label, sizeof(w->label), "Item");
		} break;

		case MKGUI_STATUSBAR: {
			w->x = 0;
			w->y = ed.canvas_h - MKGUI_STATUSBAR_HEIGHT;
			w->w = ed.canvas_w;
			w->h = MKGUI_STATUSBAR_HEIGHT;
			w->flags = MKGUI_ANCHOR_LEFT | MKGUI_ANCHOR_BOTTOM | MKGUI_ANCHOR_RIGHT;
		} break;

		case MKGUI_TOOLBAR: {
			w->x = 0;
			w->y = 0;
			for(uint32_t j = 0; j < ed.widget_count; ++j) {
				if(ed.widgets[j].type == MKGUI_MENU && ed.widgets[j].parent_id == ed.widgets[0].id) {
					w->y = ed.widgets[j].y + ed.widgets[j].h;
					break;
				}
			}
			w->w = ed.canvas_w;
			w->h = MKGUI_TOOLBAR_HEIGHT;
			w->flags = MKGUI_ANCHOR_LEFT | MKGUI_ANCHOR_TOP | MKGUI_ANCHOR_RIGHT;
		} break;

		case MKGUI_RADIO: {
			w->w = 120;
			w->h = 20;
			snprintf(w->label, sizeof(w->label), "Radio");
		} break;

		case MKGUI_PROGRESS: {
			w->w = 200;
			w->h = 20;
		} break;

		case MKGUI_TEXTAREA: {
			w->w = 200;
			w->h = 100;
		} break;

		case MKGUI_SPINBOX: {
			w->w = 100;
			w->h = 24;
		} break;

		case MKGUI_GROUP: {
			w->w = 300;
			w->h = 150;
			snprintf(w->label, sizeof(w->label), "Group");
		} break;

		case MKGUI_SPINNER: {
			w->w = 28;
			w->h = 28;
		} break;

		case MKGUI_ITEMVIEW: {
			w->w = 300;
			w->h = 200;
		} break;

		case MKGUI_PANEL: {
			w->w = 300;
			w->h = 200;
		} break;

		case MKGUI_SCROLLBAR: {
			w->w = MKGUI_SCROLLBAR_W;
			w->h = 200;
		} break;

		case MKGUI_IMAGE: {
			w->w = 200;
			w->h = 150;
		} break;

		case MKGUI_GLVIEW: {
			w->w = 300;
			w->h = 200;
		} break;

		case MKGUI_VBOX:
		case MKGUI_HBOX: {
			w->w = 300;
			w->h = 200;
		} break;

		case MKGUI_FORM: {
			w->w = 300;
			w->h = 200;
		} break;

		default: {
			w->w = 100;
			w->h = 30;
		} break;
	}

	w->tab_order = ed.widget_count;
	ed_gen_id_name(w);

	if(ed.widget_count > 0 && type != MKGUI_WINDOW) {
		w->parent_id = ed.widgets[0].id;
	}

	++ed.widget_count;
	int32_t result = (int32_t)(ed.widget_count - 1);

	if(type == MKGUI_TABS && ed.widget_count < ED_MAX_WIDGETS) {
		uint32_t tabs_id = w->id;
		struct ed_widget *tab = &ed.widgets[ed.widget_count];
		memset(tab, 0, sizeof(*tab));
		tab->type = MKGUI_TAB;
		tab->id = ed.next_id++;
		tab->parent_id = tabs_id;
		snprintf(tab->label, sizeof(tab->label), "Tab 1");
		tab->tab_order = ed.widget_count;
		ed_gen_id_name(tab);
		++ed.widget_count;
		ed_set_active_tab(tabs_id, tab->id);
	}

	if(type == MKGUI_MENU && ed.widget_count < ED_MAX_WIDGETS) {
		uint32_t menu_id = w->id;
		struct ed_widget *item = &ed.widgets[ed.widget_count];
		memset(item, 0, sizeof(*item));
		item->type = MKGUI_MENUITEM;
		item->id = ed.next_id++;
		item->parent_id = menu_id;
		snprintf(item->label, sizeof(item->label), "File");
		item->tab_order = ed.widget_count;
		ed_gen_id_name(item);
		++ed.widget_count;
	}

	return result;
}

// [=]===^=[ ed_is_descendant ]====================================[=]
static uint32_t ed_is_descendant(uint32_t widget_idx, uint32_t ancestor_id) {
	uint32_t pid = ed.widgets[widget_idx].parent_id;
	for(uint32_t depth = 0; depth < 32; ++depth) {
		if(pid == ancestor_id) {
			return 1;
		}
		if(pid == 0) {
			return 0;
		}
		uint32_t found = 0;
		for(uint32_t j = 0; j < ed.widget_count; ++j) {
			if(ed.widgets[j].id == pid) {
				pid = ed.widgets[j].parent_id;
				found = 1;
				break;
			}
		}
		if(!found) {
			return 0;
		}
	}
	return 0;
}

// [=]===^=[ ed_delete_widget_tree ]===============================[=]
static void ed_delete_widget_tree(uint32_t id) {
	for(uint32_t i = ed.widget_count; i > 0; --i) {
		uint32_t idx = i - 1;
		if(ed_is_descendant(idx, id)) {
			memmove(&ed.widgets[idx], &ed.widgets[idx + 1], (ed.widget_count - idx - 1) * sizeof(struct ed_widget));
			--ed.widget_count;
		}
	}
	for(uint32_t i = 0; i < ed.widget_count; ++i) {
		if(ed.widgets[i].id == id) {
			memmove(&ed.widgets[i], &ed.widgets[i + 1], (ed.widget_count - i - 1) * sizeof(struct ed_widget));
			--ed.widget_count;
			break;
		}
	}
}

// [=]===^=[ ed_delete_selected ]=================================[=]
static void ed_delete_selected(void) {
	if(ed.selected < 0 || (uint32_t)ed.selected >= ed.widget_count) {
		return;
	}
	if(ed.widgets[ed.selected].type == MKGUI_WINDOW) {
		return;
	}
	ed_push_undo();
	uint32_t del_id = ed.widgets[ed.selected].id;
	ed_delete_widget_tree(del_id);
	ed.selected = -1;
}

// [=]===^=[ ed_insert_child_after ]================================[=]
static uint32_t ed_insert_child_after(uint32_t parent_id) {
	if(ed.widget_count >= ED_MAX_WIDGETS) {
		return ed.widget_count;
	}
	uint32_t insert_at = ed.widget_count;
	for(uint32_t i = 0; i < ed.widget_count; ++i) {
		if(ed.widgets[i].id == parent_id) {
			insert_at = i + 1;
			for(uint32_t j = insert_at; j < ed.widget_count; ++j) {
				if(ed_is_descendant(j, parent_id)) {
					insert_at = j + 1;
				}
			}
			break;
		}
	}
	if(insert_at < ed.widget_count) {
		memmove(&ed.widgets[insert_at + 1], &ed.widgets[insert_at], (ed.widget_count - insert_at) * sizeof(struct ed_widget));
	}
	memset(&ed.widgets[insert_at], 0, sizeof(struct ed_widget));
	++ed.widget_count;
	return insert_at;
}

// [=]===^=[ ed_widget_canvas_pos ]================================[=]
static void ed_widget_canvas_pos(uint32_t idx, int32_t *out_x, int32_t *out_y) {
	struct ed_widget *w = &ed.widgets[idx];
	if(w->type == MKGUI_TAB) {
		for(uint32_t j = 0; j < ed.widget_count; ++j) {
			if(ed.widgets[j].id == w->parent_id) {
				*out_x = ed.widgets[j].x;
				*out_y = ed.widgets[j].y + MKGUI_TAB_HEIGHT;
				return;
			}
		}
	}
	*out_x = w->x;
	*out_y = w->y;
}

// [=]===^=[ ed_convert_to_layout ]================================[=]
static void ed_convert_to_layout(uint32_t idx, int32_t *lx, int32_t *ly, int32_t *lw, int32_t *lh) {
	struct ed_widget *ew = &ed.widgets[idx];
	int32_t px = 0, py = 0, pw = 0, ph = 0;
	for(uint32_t j = 0; j < ed.widget_count; ++j) {
		if(ed.widgets[j].id == ew->parent_id) {
			ed_widget_canvas_pos(j, &px, &py);
			pw = ed.widgets[j].w;
			ph = ed.widgets[j].h;
			break;
		}
	}

	int32_t rel_x = ew->x - px;
	int32_t rel_y = ew->y - py;
	int32_t w = ew->w;
	int32_t h = ew->h;
	uint32_t flags = ew->flags;

	if((flags & MKGUI_ANCHOR_LEFT) && (flags & MKGUI_ANCHOR_RIGHT)) {
		w = pw - rel_x - w;
		if(w < 0) {
			w = 0;
		}

	} else if(flags & MKGUI_ANCHOR_RIGHT) {
		rel_x = pw - rel_x - w;
	}

	if((flags & MKGUI_ANCHOR_TOP) && (flags & MKGUI_ANCHOR_BOTTOM)) {
		h = ph - rel_y - h;
		if(h < 0) {
			h = 0;
		}

	} else if(flags & MKGUI_ANCHOR_BOTTOM) {
		rel_y = ph - rel_y - h;
	}

	*lx = rel_x;
	*ly = rel_y;
	*lw = w;
	*lh = h;
}

// [=]===^=[ ed_tab_header_hit ]===================================[=]
static uint32_t ed_tab_header_hit(struct mkgui_ctx *ctx, int32_t tabs_idx, int32_t lx, int32_t ly) {
	struct ed_widget *tabs_w = &ed.widgets[tabs_idx];
	int32_t rel_x = lx - tabs_w->x;
	int32_t rel_y = ly - tabs_w->y;
	if(rel_y < 0 || rel_y >= MKGUI_TAB_HEIGHT) {
		return 0;
	}
	int32_t tab_x = 0;
	for(uint32_t i = 0; i < ed.widget_count; ++i) {
		if(ed.widgets[i].type == MKGUI_TAB && ed.widgets[i].parent_id == tabs_w->id) {
			int32_t tw = text_width(ctx, ed.widgets[i].label) + 20;
			if(rel_x >= tab_x && rel_x < tab_x + tw) {
				return ed.widgets[i].id;
			}
			tab_x += tw;
		}
	}
	return 0;
}

// [=]===^=[ ed_snap ]============================================[=]
static int32_t ed_snap(int32_t v) {
	if(ed.grid_size <= 1) {
		return v;
	}
	return ((v + ed.grid_size / 2) / ed.grid_size) * ed.grid_size;
}

// [=]===^=[ ed_canvas_hit ]======================================[=]
static int32_t ed_canvas_hit(int32_t cx, int32_t cy) {
	for(int32_t i = (int32_t)ed.widget_count - 1; i >= 0; --i) {
		struct ed_widget *w = &ed.widgets[i];
		if(w->type == MKGUI_WINDOW || w->type == MKGUI_TAB || w->type == MKGUI_MENUITEM) {
			continue;
		}
		if(!ed_is_tab_child_visible((uint32_t)i)) {
			continue;
		}
		if(w->w <= 0 || w->h <= 0) {
			continue;
		}
		if(cx >= w->x && cx < w->x + w->w && cy >= w->y && cy < w->y + w->h) {
			return i;
		}
	}
	return -1;
}

// [=]===^=[ ed_handle_hit ]======================================[=]
static int32_t ed_handle_hit(int32_t cx, int32_t cy) {
	if(ed.selected < 0) {
		return -1;
	}
	struct ed_widget *w = &ed.widgets[ed.selected];
	int32_t hx[] = { w->x, w->x + w->w / 2, w->x + w->w, w->x + w->w, w->x + w->w, w->x + w->w / 2, w->x, w->x };
	int32_t hy[] = { w->y, w->y, w->y, w->y + w->h / 2, w->y + w->h, w->y + w->h, w->y + w->h, w->y + w->h / 2 };
	for(int32_t i = 0; i < 8; ++i) {
		if(cx >= hx[i] - 4 && cx <= hx[i] + 4 && cy >= hy[i] - 4 && cy <= hy[i] + 4) {
			return i;
		}
	}
	return -1;
}

#define ED_EDGE_LEFT   1
#define ED_EDGE_TOP    2
#define ED_EDGE_RIGHT  4
#define ED_EDGE_BOTTOM 8
#define ED_CANVAS_MIN  64
#define ED_EDGE_THRESH 5

// [=]===^=[ ed_canvas_edge_hit ]==================================[=]
static uint32_t ed_canvas_edge_hit(int32_t lx, int32_t ly) {
	uint32_t edges = 0;
	int32_t cw = ed.canvas_w;
	int32_t ch = ed.canvas_h;
	int32_t t = ED_EDGE_THRESH;

	if(lx >= -t && lx <= t && ly >= -t && ly <= ch + t) {
		edges |= ED_EDGE_LEFT;
	}
	if(lx >= cw - t && lx <= cw + t && ly >= -t && ly <= ch + t) {
		edges |= ED_EDGE_RIGHT;
	}
	if(ly >= -t && ly <= t && lx >= -t && lx <= cw + t) {
		edges |= ED_EDGE_TOP;
	}
	if(ly >= ch - t && ly <= ch + t && lx >= -t && lx <= cw + t) {
		edges |= ED_EDGE_BOTTOM;
	}
	return edges;
}

// ---------------------------------------------------------------------------
// Canvas rendering (render callback)
// ---------------------------------------------------------------------------

// [=]===^=[ ed_render_canvas ]===================================[=]
static void ed_render_canvas(struct mkgui_ctx *ctx, void *userdata) {
	(void)userdata;

	int32_t ci = find_widget_idx(ctx, ED_CANVAS_LBL);
	if(ci < 0) {
		return;
	}
	int32_t cx = ctx->rects[ci].x;
	int32_t cy = ctx->rects[ci].y;
	int32_t cw = ctx->rects[ci].w;
	int32_t ch = ctx->rects[ci].h;

	draw_rect_fill(ctx->pixels, ctx->win_w, ctx->win_h, cx, cy, cw, ch, 0xFF3A3A3A);

	int32_t win_x = cx + (cw - ed.canvas_w) / 2;
	int32_t win_y = cy + (ch - ed.canvas_h) / 2;

	draw_rect_fill(ctx->pixels, ctx->win_w, ctx->win_h, win_x, win_y, ed.canvas_w, ed.canvas_h, ctx->theme.bg);
	draw_rect_border(ctx->pixels, ctx->win_w, ctx->win_h, win_x, win_y, ed.canvas_w, ed.canvas_h, 0xFF555555);

	if(ed.grid_size >= 4) {
		for(int32_t gy = 0; gy < ed.canvas_h; gy += ed.grid_size) {
			for(int32_t gx = 0; gx < ed.canvas_w; gx += ed.grid_size) {
				int32_t px = win_x + gx;
				int32_t py = win_y + gy;
				if(px >= cx && px < cx + cw && py >= cy && py < cy + ch) {
					if(px >= 0 && px < ctx->win_w && py >= 0 && py < ctx->win_h) {
						ctx->pixels[py * ctx->win_w + px] = 0xFF4A4A4A;
					}
				}
			}
		}
	}

	// Save ctx state
	static struct mkgui_widget saved_widgets[MKGUI_MAX_WIDGETS];
	static struct { int32_t x, y, w, h; } saved_rects[MKGUI_MAX_WIDGETS];
	uint32_t saved_count = ctx->widget_count;
	uint32_t saved_hover = ctx->hover_id;
	uint32_t saved_focus = ctx->focus_id;
	uint32_t saved_press = ctx->press_id;
	uint32_t saved_input_count = ctx->input_count;
	uint32_t saved_dropdown_count = ctx->dropdown_count;
	uint32_t saved_slider_count = ctx->slider_count;
	uint32_t saved_tab_count = ctx->tab_count;
	uint32_t saved_listv_count = ctx->listv_count;
	uint32_t saved_split_count = ctx->split_count;
	uint32_t saved_treeview_count = ctx->treeview_count;
	uint32_t saved_statusbar_count = ctx->statusbar_count;
	uint32_t saved_spinbox_count = ctx->spinbox_count;
	uint32_t saved_progress_count = ctx->progress_count;
	uint32_t saved_textarea_count = ctx->textarea_count;
	uint32_t saved_box_scroll_count = ctx->box_scroll_count;
	memcpy(saved_widgets, ctx->widgets, saved_count * sizeof(struct mkgui_widget));
	memcpy(saved_rects, ctx->rects, saved_count * sizeof(saved_rects[0]));

	// Build preview widgets from editor state
	for(uint32_t i = 0; i < ed.widget_count; ++i) {
		struct ed_widget *ew = &ed.widgets[i];
		struct mkgui_widget *tw = &ctx->widgets[i];
		tw->type = ew->type;
		tw->id = ew->id;
		size_t slen = strlen(ew->label);
		if(slen >= MKGUI_MAX_TEXT) {
			slen = MKGUI_MAX_TEXT - 1;
		}
		memcpy(tw->label, ew->label, slen);
		tw->label[slen] = '\0';
		tw->parent_id = ew->parent_id;
		tw->x = ew->x;
		tw->y = ew->y;
		tw->w = ew->w;
		tw->h = ew->h;
		tw->flags = ew->flags;
		memcpy(tw->icon, ew->icon, MKGUI_ICON_NAME_LEN);

		if(ew->type == MKGUI_WINDOW) {
			ctx->rects[i].x = win_x;
			ctx->rects[i].y = win_y;
			ctx->rects[i].w = ed.canvas_w;
			ctx->rects[i].h = ed.canvas_h;
		} else {
			ctx->rects[i].x = win_x + ew->x;
			ctx->rects[i].y = win_y + ew->y;
			ctx->rects[i].w = ew->w;
			ctx->rects[i].h = ew->h;
		}
	}
	ctx->widget_count = ed.widget_count;
	ctx->hover_id = 0;
	ctx->focus_id = 0;
	ctx->press_id = 0;

	// Auto-layout pass for VBOX/HBOX/FORM children
	for(uint32_t pass = 0; pass < 4; ++pass) {
		for(uint32_t i = 0; i < ctx->widget_count; ++i) {
			if(ctx->widgets[i].type == MKGUI_WINDOW) {
				continue;
			}
			int32_t pidx = find_widget_idx(ctx, ctx->widgets[i].parent_id);
			if(pidx < 0) {
				continue;
			}
			struct mkgui_widget *parent = &ctx->widgets[pidx];
			if(parent->type != MKGUI_VBOX && parent->type != MKGUI_HBOX && parent->type != MKGUI_FORM) {
				continue;
			}

			int32_t px = ctx->rects[pidx].x;
			int32_t py = ctx->rects[pidx].y;
			int32_t pw = ctx->rects[pidx].w;
			int32_t ph = ctx->rects[pidx].h;

			if(parent->flags & MKGUI_PANEL_BORDER) {
				px += MKGUI_BOX_PAD;
				py += MKGUI_BOX_PAD;
				pw -= MKGUI_BOX_PAD * 2;
				ph -= MKGUI_BOX_PAD * 2;
			}

			uint32_t child_count = 0;
			for(uint32_t j = 0; j < ctx->widget_count; ++j) {
				if(ctx->widgets[j].parent_id == parent->id && j != (uint32_t)pidx && !(ctx->widgets[j].flags & MKGUI_HIDDEN)) {
					++child_count;
				}
			}

			if(parent->type == MKGUI_VBOX) {
				int32_t fixed_total = 0;
				uint32_t flex_count = 0;
				for(uint32_t j = 0; j < ctx->widget_count; ++j) {
					if(ctx->widgets[j].parent_id == parent->id && j != (uint32_t)pidx && !(ctx->widgets[j].flags & MKGUI_HIDDEN)) {
						if(ctx->widgets[j].h > 0) {
							fixed_total += ctx->widgets[j].h;
						} else {
							++flex_count;
						}
					}
				}
				int32_t gap_total = child_count > 1 ? (int32_t)(child_count - 1) * MKGUI_BOX_GAP : 0;
				int32_t remaining = ph - fixed_total - gap_total;
				if(remaining < 0) {
					remaining = 0;
				}
				int32_t flex_h = flex_count > 0 ? remaining / (int32_t)flex_count : 0;

				int32_t cy = py;
				for(uint32_t j = 0; j < ctx->widget_count; ++j) {
					if(ctx->widgets[j].parent_id == parent->id && j != (uint32_t)pidx && !(ctx->widgets[j].flags & MKGUI_HIDDEN)) {
						int32_t ch = ctx->widgets[j].h > 0 ? ctx->widgets[j].h : flex_h;
						if(j == i) {
							ctx->rects[i].x = px;
							ctx->rects[i].y = cy;
							ctx->rects[i].w = pw;
							ctx->rects[i].h = ch;
							break;
						}
						cy += ch + MKGUI_BOX_GAP;
					}
				}

			} else if(parent->type == MKGUI_HBOX) {
				int32_t fixed_total = 0;
				uint32_t flex_count = 0;
				for(uint32_t j = 0; j < ctx->widget_count; ++j) {
					if(ctx->widgets[j].parent_id == parent->id && j != (uint32_t)pidx && !(ctx->widgets[j].flags & MKGUI_HIDDEN)) {
						if(ctx->widgets[j].w > 0) {
							fixed_total += ctx->widgets[j].w;
						} else {
							++flex_count;
						}
					}
				}
				int32_t gap_total = child_count > 1 ? (int32_t)(child_count - 1) * MKGUI_BOX_GAP : 0;
				int32_t remaining = pw - fixed_total - gap_total;
				if(remaining < 0) {
					remaining = 0;
				}
				int32_t flex_w = flex_count > 0 ? remaining / (int32_t)flex_count : 0;

				int32_t cx = px;
				for(uint32_t j = 0; j < ctx->widget_count; ++j) {
					if(ctx->widgets[j].parent_id == parent->id && j != (uint32_t)pidx && !(ctx->widgets[j].flags & MKGUI_HIDDEN)) {
						int32_t cw = ctx->widgets[j].w > 0 ? ctx->widgets[j].w : flex_w;
						if(j == i) {
							ctx->rects[i].x = cx;
							ctx->rects[i].y = py;
							ctx->rects[i].w = cw;
							ctx->rects[i].h = ph;
							break;
						}
						cx += cw + MKGUI_BOX_GAP;
					}
				}

			} else {
				int32_t label_w = 0;
				uint32_t pair_idx = 0;
				for(uint32_t j = 0; j < ctx->widget_count; ++j) {
					if(ctx->widgets[j].parent_id == parent->id && j != (uint32_t)pidx && !(ctx->widgets[j].flags & MKGUI_HIDDEN)) {
						if((pair_idx & 1) == 0) {
							int32_t tw = text_width(ctx, ctx->widgets[j].label) + 8;
							if(tw > label_w) {
								label_w = tw;
							}
						}
						++pair_idx;
					}
				}

				pair_idx = 0;
				for(uint32_t j = 0; j < ctx->widget_count; ++j) {
					if(ctx->widgets[j].parent_id == parent->id && j != (uint32_t)pidx && !(ctx->widgets[j].flags & MKGUI_HIDDEN)) {
						int32_t row = (int32_t)(pair_idx / 2);
						int32_t row_h = 24;
						uint32_t is_label = (pair_idx & 1) == 0;
						if(j == i) {
							if(is_label) {
								ctx->rects[i].x = px;
								ctx->rects[i].y = py + row * (row_h + MKGUI_BOX_GAP);
								ctx->rects[i].w = label_w;
								ctx->rects[i].h = row_h;
							} else {
								ctx->rects[i].x = px + label_w;
								ctx->rects[i].y = py + row * (row_h + MKGUI_BOX_GAP);
								ctx->rects[i].w = pw - label_w;
								ctx->rects[i].h = row_h;
							}
							break;
						}
						++pair_idx;
					}
				}
			}
		}
	}

	// Append preview tabs entries after editor entries
	for(uint32_t i = 0; i < ctx->widget_count; ++i) {
		if(ctx->widgets[i].type == MKGUI_TABS && ctx->tab_count < 32) {
			struct mkgui_tabs_data *td = &ctx->tabs[ctx->tab_count++];
			td->widget_id = ctx->widgets[i].id;
			td->active_tab = 0;
			for(uint32_t j = 0; j < ctx->widget_count; ++j) {
				if(ctx->widgets[j].type == MKGUI_TAB && ctx->widgets[j].parent_id == ctx->widgets[i].id) {
					td->active_tab = ctx->widgets[j].id;
					break;
				}
			}
		}
	}

	// Set active tabs to match editor tab state
	for(uint32_t i = 0; i < ed.tab_state_count; ++i) {
		for(uint32_t j = 0; j < ctx->tab_count; ++j) {
			if(ctx->tabs[j].widget_id == ed.tab_states[i].tabs_id) {
				ctx->tabs[j].active_tab = ed.tab_states[i].active_id;
				break;
			}
		}
	}

	// Anchor preview pass
	for(uint32_t pass = 0; pass < 4; ++pass) {
		for(uint32_t i = 0; i < ctx->widget_count; ++i) {
			struct mkgui_widget *w = &ctx->widgets[i];
			if(w->type == MKGUI_WINDOW) {
				continue;
			}
			uint32_t has_anchor = w->flags & (MKGUI_ANCHOR_LEFT | MKGUI_ANCHOR_TOP | MKGUI_ANCHOR_RIGHT | MKGUI_ANCHOR_BOTTOM);
			if(!has_anchor) {
				continue;
			}
			int32_t pidx = find_widget_idx(ctx, w->parent_id);
			if(pidx < 0) {
				continue;
			}
			struct mkgui_widget *parent = &ctx->widgets[pidx];
			if(parent->type == MKGUI_VBOX || parent->type == MKGUI_HBOX || parent->type == MKGUI_FORM) {
				continue;
			}

			int32_t px = ctx->rects[pidx].x;
			int32_t py = ctx->rects[pidx].y;
			int32_t pw = ctx->rects[pidx].w;
			int32_t ph = ctx->rects[pidx].h;

			if(parent->type == MKGUI_TAB) {
				px += 2;
				py += MKGUI_TAB_HEIGHT + 2;
				pw -= 4;
				ph -= MKGUI_TAB_HEIGHT + 4;
			}
			if(parent->type == MKGUI_GROUP) {
				int32_t gtop = ctx->font_height + 4;
				int32_t gpad = 6;
				px += gpad;
				py += gtop;
				pw -= gpad * 2;
				ph -= gtop + gpad;
			}

			int32_t ox = ctx->rects[i].x - px;
			int32_t oy = ctx->rects[i].y - py;
			int32_t ow = ctx->rects[i].w;
			int32_t oh = ctx->rects[i].h;

			int32_t margin_r = pw - ox - ow;
			if(margin_r < 0) {
				margin_r = 0;
			}
			int32_t margin_b = ph - oy - oh;
			if(margin_b < 0) {
				margin_b = 0;
			}

			if((w->flags & MKGUI_ANCHOR_LEFT) && (w->flags & MKGUI_ANCHOR_RIGHT)) {
				ctx->rects[i].x = px + ox;
				ctx->rects[i].w = pw - ox - margin_r;
			} else if(w->flags & MKGUI_ANCHOR_RIGHT) {
				ctx->rects[i].x = px + pw - ow - margin_r;
			}

			if((w->flags & MKGUI_ANCHOR_TOP) && (w->flags & MKGUI_ANCHOR_BOTTOM)) {
				ctx->rects[i].y = py + oy;
				ctx->rects[i].h = ph - oy - margin_b;
			} else if(w->flags & MKGUI_ANCHOR_BOTTOM) {
				ctx->rects[i].y = py + ph - oh - margin_b;
			}
		}
	}

	// Render preview widgets
	for(uint32_t i = 0; i < ctx->widget_count; ++i) {
		if(ctx->widgets[i].type == MKGUI_WINDOW) {
			continue;
		}
		if(!ed_is_tab_child_visible(i)) {
			continue;
		}
		if(ctx->rects[i].w <= 0 || ctx->rects[i].h <= 0) {
			continue;
		}
		render_widget(ctx, i);
	}

	// Draw dashed outlines for invisible containers
	for(uint32_t i = 0; i < ctx->widget_count; ++i) {
		uint32_t t = ctx->widgets[i].type;
		uint32_t fl = ctx->widgets[i].flags;
		uint32_t needs_outline = 0;
		if(t == MKGUI_VBOX || t == MKGUI_HBOX || t == MKGUI_FORM) {
			if(!(fl & MKGUI_PANEL_BORDER)) {
				needs_outline = 1;
			}
		} else if(t == MKGUI_TABS || t == MKGUI_HSPLIT || t == MKGUI_VSPLIT) {
			needs_outline = 1;
		} else if(t == MKGUI_PANEL) {
			if(!(fl & (MKGUI_PANEL_BORDER | MKGUI_PANEL_SUNKEN))) {
				needs_outline = 1;
			}
		}
		if(needs_outline) {
			draw_rect_dashed(ctx->pixels, ctx->win_w, ctx->win_h, ctx->rects[i].x, ctx->rects[i].y, ctx->rects[i].w, ctx->rects[i].h, 0xFF666666, 4);
		}
	}

	// Restore ctx state
	memcpy(ctx->widgets, saved_widgets, saved_count * sizeof(struct mkgui_widget));
	memcpy(ctx->rects, saved_rects, saved_count * sizeof(saved_rects[0]));
	ctx->widget_count = saved_count;
	ctx->hover_id = saved_hover;
	ctx->focus_id = saved_focus;
	ctx->press_id = saved_press;
	ctx->input_count = saved_input_count;
	ctx->dropdown_count = saved_dropdown_count;
	ctx->slider_count = saved_slider_count;
	ctx->tab_count = saved_tab_count;
	ctx->listv_count = saved_listv_count;
	ctx->split_count = saved_split_count;
	ctx->treeview_count = saved_treeview_count;
	ctx->statusbar_count = saved_statusbar_count;
	ctx->spinbox_count = saved_spinbox_count;
	ctx->progress_count = saved_progress_count;
	ctx->textarea_count = saved_textarea_count;
	ctx->box_scroll_count = saved_box_scroll_count;

	// Selection handles on top
	for(uint32_t i = 0; i < ed.widget_count; ++i) {
		if((int32_t)i == ed.selected) {
			struct ed_widget *w = &ed.widgets[i];
			int32_t wx = win_x + w->x;
			int32_t wy = win_y + w->y;
			int32_t ww = w->w;
			int32_t wh = w->h;

			draw_rect_border(ctx->pixels, ctx->win_w, ctx->win_h, wx - 1, wy - 1, ww + 2, wh + 2, 0xFF007ACC);

			int32_t hx[] = { wx, wx + ww / 2, wx + ww, wx + ww, wx + ww, wx + ww / 2, wx, wx };
			int32_t hy[] = { wy, wy, wy, wy + wh / 2, wy + wh, wy + wh, wy + wh, wy + wh / 2 };
			for(int32_t j = 0; j < 8; ++j) {
				draw_rect_fill(ctx->pixels, ctx->win_w, ctx->win_h, hx[j] - 3, hy[j] - 3, 6, 6, 0xFF007ACC);
			}
			break;
		}
	}

	uint32_t hc = 0xFF888888;
	int32_t hs = 4;
	int32_t mx = win_x + ed.canvas_w / 2;
	int32_t my = win_y + ed.canvas_h / 2;
	int32_t rx = win_x + ed.canvas_w;
	int32_t by = win_y + ed.canvas_h;
	draw_rect_fill(ctx->pixels, ctx->win_w, ctx->win_h, mx - hs, win_y - hs, hs * 2, hs * 2, hc);
	draw_rect_fill(ctx->pixels, ctx->win_w, ctx->win_h, mx - hs, by - hs, hs * 2, hs * 2, hc);
	draw_rect_fill(ctx->pixels, ctx->win_w, ctx->win_h, win_x - hs, my - hs, hs * 2, hs * 2, hc);
	draw_rect_fill(ctx->pixels, ctx->win_w, ctx->win_h, rx - hs, my - hs, hs * 2, hs * 2, hc);
	draw_rect_fill(ctx->pixels, ctx->win_w, ctx->win_h, win_x - hs, win_y - hs, hs * 2, hs * 2, hc);
	draw_rect_fill(ctx->pixels, ctx->win_w, ctx->win_h, rx - hs, win_y - hs, hs * 2, hs * 2, hc);
	draw_rect_fill(ctx->pixels, ctx->win_w, ctx->win_h, win_x - hs, by - hs, hs * 2, hs * 2, hc);
	draw_rect_fill(ctx->pixels, ctx->win_w, ctx->win_h, rx - hs, by - hs, hs * 2, hs * 2, hc);

	if(ed.placement_type) {
		const char *placing = ed_type_name(ed.placement_type);
		char buf[64];
		snprintf(buf, sizeof(buf), "Placing: %s (click canvas, Esc to cancel)", placing);
		push_text(cx + 4, cy + 4, buf, 0xFFFFFF00);
	}

	char size_buf[32];
	snprintf(size_buf, sizeof(size_buf), "%dx%d", ed.canvas_w, ed.canvas_h);
	push_text(win_x + 2, by + 4, size_buf, 0xFF888888);
}

// ---------------------------------------------------------------------------
// Treeview sync
// ---------------------------------------------------------------------------

// [=]===^=[ ed_sync_tree ]=======================================[=]
static void ed_sync_tree(struct mkgui_ctx *ctx) {
	mkgui_treeview_setup(ctx, ED_TREE);
	for(uint32_t i = 0; i < ed.widget_count; ++i) {
		struct ed_widget *w = &ed.widgets[i];
		char buf[128];
		snprintf(buf, sizeof(buf), "%s: %s", ed_type_name(w->type), w->id_name);
		uint32_t parent_node = 0;
		if(w->parent_id != 0) {
			parent_node = w->parent_id;
		}
		mkgui_treeview_add(ctx, ED_TREE, w->id, parent_node, buf);
	}

	for(uint32_t i = 0; i < 8; ++i) {
		struct mkgui_treeview_data *tv = find_treeview_data(ctx, ED_TREE);
		if(tv) {
			for(uint32_t j = 0; j < tv->node_count; ++j) {
				tv->nodes[j].expanded = 1;
			}
		}
	}

	dirty_all(ctx);
}

// [=]===^=[ ed_find_menu_root ]===================================[=]
static uint32_t ed_find_menu_root(uint32_t widget_idx) {
	struct ed_widget *w = &ed.widgets[widget_idx];
	if(w->type == MKGUI_MENU) {
		return w->id;
	}
	uint32_t pid = w->parent_id;
	for(uint32_t depth = 0; depth < 32; ++depth) {
		int32_t idx = ed_find_widget(pid);
		if(idx < 0) {
			break;
		}
		if(ed.widgets[idx].type == MKGUI_MENU) {
			return ed.widgets[idx].id;
		}
		pid = ed.widgets[idx].parent_id;
	}
	return 0;
}

// [=]===^=[ ed_sync_menu_tree ]===================================[=]
static void ed_sync_menu_tree(struct mkgui_ctx *ctx) {
	struct mkgui_widget *tw = find_widget(ctx, ED_MENU_TREE);
	if(!tw) {
		return;
	}

	if(ed.selected < 0 || (uint32_t)ed.selected >= ed.widget_count) {
		tw->flags |= MKGUI_HIDDEN;
		return;
	}

	struct ed_widget *sel = &ed.widgets[ed.selected];
	if(sel->type != MKGUI_MENU && sel->type != MKGUI_MENUITEM) {
		tw->flags |= MKGUI_HIDDEN;
		return;
	}

	uint32_t menu_id = ed_find_menu_root((uint32_t)ed.selected);
	if(!menu_id) {
		tw->flags |= MKGUI_HIDDEN;
		return;
	}

	tw->flags &= ~MKGUI_HIDDEN;

	mkgui_treeview_setup(ctx, ED_MENU_TREE);

	int32_t menu_idx = ed_find_widget(menu_id);
	if(menu_idx >= 0) {
		struct ed_widget *mw = &ed.widgets[menu_idx];
		char buf[128];
		snprintf(buf, sizeof(buf), "%s: %s", ed_type_name(mw->type), mw->id_name);
		mkgui_treeview_add(ctx, ED_MENU_TREE, mw->id, 0, buf);
	}

	for(uint32_t i = 0; i < ed.widget_count; ++i) {
		struct ed_widget *w = &ed.widgets[i];
		if(w->type == MKGUI_MENUITEM && ed_is_descendant(i, menu_id)) {
			char buf[128];
			snprintf(buf, sizeof(buf), "%s: %s", ed_type_name(w->type), w->label[0] ? w->label : w->id_name);
			mkgui_treeview_add(ctx, ED_MENU_TREE, w->id, w->parent_id, buf);
		}
	}

	struct mkgui_treeview_data *tv = find_treeview_data(ctx, ED_MENU_TREE);
	if(tv) {
		for(uint32_t j = 0; j < tv->node_count; ++j) {
			tv->nodes[j].expanded = 1;
		}
		tv->selected_node = (int32_t)sel->id;
	}

	dirty_all(ctx);
}

// ---------------------------------------------------------------------------
// Property panel sync
// ---------------------------------------------------------------------------

// [=]===^=[ ed_sync_parent_dropdown ]=============================[=]
static void ed_sync_parent_dropdown(struct mkgui_ctx *ctx) {
	const char *items[ED_MAX_WIDGETS];
	static char item_bufs[ED_MAX_WIDGETS][80];
	uint32_t count = 0;

	for(uint32_t i = 0; i < ed.widget_count; ++i) {
		struct ed_widget *ew = &ed.widgets[i];
		if(ew->type == MKGUI_WINDOW || ew->type == MKGUI_TABS || ew->type == MKGUI_TAB ||
		   ew->type == MKGUI_HSPLIT || ew->type == MKGUI_VSPLIT || ew->type == MKGUI_GROUP || ew->type == MKGUI_PANEL ||
		   ew->type == MKGUI_VBOX || ew->type == MKGUI_HBOX || ew->type == MKGUI_FORM) {
			snprintf(item_bufs[count], sizeof(item_bufs[count]), "%u: %s (%s)", ew->id, ew->id_name[0] ? ew->id_name : ew->label, ed_type_name(ew->type));
			items[count] = item_bufs[count];
			++count;
		}
	}

	if(count == 0) {
		return;
	}

	mkgui_dropdown_setup(ctx, ED_PROP_PARENT_DRP, items, count);

	if(ed.selected >= 0 && (uint32_t)ed.selected < ed.widget_count) {
		uint32_t pid = ed.widgets[ed.selected].parent_id;
		uint32_t sel_idx = 0;
		uint32_t j = 0;
		for(uint32_t i = 0; i < ed.widget_count; ++i) {
			struct ed_widget *ew = &ed.widgets[i];
			if(ew->type == MKGUI_WINDOW || ew->type == MKGUI_TABS || ew->type == MKGUI_TAB ||
			   ew->type == MKGUI_HSPLIT || ew->type == MKGUI_VSPLIT ||
			   ew->type == MKGUI_MENU || ew->type == MKGUI_MENUITEM || ew->type == MKGUI_GROUP || ew->type == MKGUI_PANEL ||
			   ew->type == MKGUI_VBOX || ew->type == MKGUI_HBOX || ew->type == MKGUI_FORM) {
				if(ew->id == pid) {
					sel_idx = j;
				}
				++j;
			}
		}
		struct mkgui_dropdown_data *dd = find_dropdown_data(ctx, ED_PROP_PARENT_DRP);
		if(dd) {
			dd->selected = (int32_t)sel_idx;
		}
	}
}

// [=]===^=[ ed_apply_parent_dropdown ]============================[=]
static void ed_apply_parent_dropdown(struct mkgui_ctx *ctx) {
	if(ed.selected < 0 || (uint32_t)ed.selected >= ed.widget_count) {
		return;
	}

	struct mkgui_dropdown_data *dd = find_dropdown_data(ctx, ED_PROP_PARENT_DRP);
	if(!dd || dd->selected < 0) {
		return;
	}

	uint32_t j = 0;
	for(uint32_t i = 0; i < ed.widget_count; ++i) {
		struct ed_widget *ew = &ed.widgets[i];
		if(ew->type == MKGUI_WINDOW || ew->type == MKGUI_TABS || ew->type == MKGUI_TAB ||
		   ew->type == MKGUI_HSPLIT || ew->type == MKGUI_VSPLIT ||
		   ew->type == MKGUI_GROUP || ew->type == MKGUI_PANEL ||
		   ew->type == MKGUI_VBOX || ew->type == MKGUI_HBOX || ew->type == MKGUI_FORM) {
			if(j == (uint32_t)dd->selected) {
				ed.widgets[ed.selected].parent_id = ew->id;
				ed_sync_tree(ctx);
				dirty_all(ctx);
				return;
			}
			++j;
		}
	}
}

// [=]===^=[ ed_sync_props ]======================================[=]
static void ed_sync_props(struct mkgui_ctx *ctx) {
	if(ed.selected < 0 || (uint32_t)ed.selected >= ed.widget_count) {
		mkgui_label_set(ctx, ED_PROP_TYPE_VAL, "(none)");
		mkgui_input_set(ctx, ED_PROP_ID_INP, "");
		mkgui_input_set(ctx, ED_PROP_LABEL_INP, "");
		mkgui_input_set(ctx, ED_PROP_ICON_INP, "");
		mkgui_spinbox_set(ctx, ED_PROP_X_SPN, 0);
		mkgui_spinbox_set(ctx, ED_PROP_Y_SPN, 0);
		mkgui_spinbox_set(ctx, ED_PROP_W_SPN, 0);
		mkgui_spinbox_set(ctx, ED_PROP_H_SPN, 0);
		mkgui_spinbox_set(ctx, ED_PROP_TAB_SPN, 0);
		struct mkgui_widget *hb;
		hb = find_widget(ctx, ED_PROP_BTN_HBOX); if(hb) { hb->flags |= MKGUI_HIDDEN; }
		hb = find_widget(ctx, ED_PROP_ADD_TAB);  if(hb) { hb->flags |= MKGUI_HIDDEN; }
		hb = find_widget(ctx, ED_PROP_REM_TAB);  if(hb) { hb->flags |= MKGUI_HIDDEN; }
		hb = find_widget(ctx, ED_PROP_ADD_ITEM); if(hb) { hb->flags |= MKGUI_HIDDEN; }
		hb = find_widget(ctx, ED_PROP_REM_ITEM); if(hb) { hb->flags |= MKGUI_HIDDEN; }
		hb = find_widget(ctx, ED_MENU_TREE);     if(hb) { hb->flags |= MKGUI_HIDDEN; }
		return;
	}

	struct ed_widget *w = &ed.widgets[ed.selected];
	mkgui_label_set(ctx, ED_PROP_TYPE_VAL, ed_type_name(w->type));
	mkgui_input_set(ctx, ED_PROP_ID_INP, w->id_name);
	mkgui_input_set(ctx, ED_PROP_LABEL_INP, w->label);
	mkgui_input_set(ctx, ED_PROP_ICON_INP, w->icon);
	mkgui_spinbox_set(ctx, ED_PROP_X_SPN, w->x);
	mkgui_spinbox_set(ctx, ED_PROP_Y_SPN, w->y);
	mkgui_spinbox_set(ctx, ED_PROP_W_SPN, w->w);
	mkgui_spinbox_set(ctx, ED_PROP_H_SPN, w->h);
	mkgui_spinbox_set(ctx, ED_PROP_TAB_SPN, (int32_t)w->tab_order);

	struct mkgui_widget *fl;
	fl = find_widget(ctx, ED_PROP_FL_LEFT);
	if(fl) { if(w->flags & MKGUI_ANCHOR_LEFT) { fl->flags |= MKGUI_CHECKED; } else { fl->flags &= ~MKGUI_CHECKED; } }
	fl = find_widget(ctx, ED_PROP_FL_TOP);
	if(fl) { if(w->flags & MKGUI_ANCHOR_TOP) { fl->flags |= MKGUI_CHECKED; } else { fl->flags &= ~MKGUI_CHECKED; } }
	fl = find_widget(ctx, ED_PROP_FL_RIGHT);
	if(fl) { if(w->flags & MKGUI_ANCHOR_RIGHT) { fl->flags |= MKGUI_CHECKED; } else { fl->flags &= ~MKGUI_CHECKED; } }
	fl = find_widget(ctx, ED_PROP_FL_BOTTOM);
	if(fl) { if(w->flags & MKGUI_ANCHOR_BOTTOM) { fl->flags |= MKGUI_CHECKED; } else { fl->flags &= ~MKGUI_CHECKED; } }
	fl = find_widget(ctx, ED_PROP_FL_VIRTUAL);
	if(fl) { if(w->flags & MKGUI_VIRTUAL) { fl->flags |= MKGUI_CHECKED; } else { fl->flags &= ~MKGUI_CHECKED; } }
	fl = find_widget(ctx, ED_PROP_FL_HIDDEN);
	if(fl) { if(w->flags & MKGUI_HIDDEN) { fl->flags |= MKGUI_CHECKED; } else { fl->flags &= ~MKGUI_CHECKED; } }
	fl = find_widget(ctx, ED_PROP_FL_DISABLED);
	if(fl) { if(w->flags & MKGUI_DISABLED) { fl->flags |= MKGUI_CHECKED; } else { fl->flags &= ~MKGUI_CHECKED; } }
	fl = find_widget(ctx, ED_PROP_FL_CHECKED);
	if(fl) { if(w->flags & MKGUI_CHECKED) { fl->flags |= MKGUI_CHECKED; } else { fl->flags &= ~MKGUI_CHECKED; } }
	fl = find_widget(ctx, ED_PROP_FL_SEPARATOR);
	if(fl) { if(w->flags & MKGUI_SEPARATOR) { fl->flags |= MKGUI_CHECKED; } else { fl->flags &= ~MKGUI_CHECKED; } }
	fl = find_widget(ctx, ED_PROP_FL_MENUCHECK);
	if(fl) { if(w->flags & MKGUI_MENU_CHECK) { fl->flags |= MKGUI_CHECKED; } else { fl->flags &= ~MKGUI_CHECKED; } }
	fl = find_widget(ctx, ED_PROP_FL_MENURADIO);
	if(fl) { if(w->flags & MKGUI_MENU_RADIO) { fl->flags |= MKGUI_CHECKED; } else { fl->flags &= ~MKGUI_CHECKED; } }
	fl = find_widget(ctx, ED_PROP_FL_REGTOP);
	if(fl) { if(w->flags & MKGUI_REGION_TOP) { fl->flags |= MKGUI_CHECKED; } else { fl->flags &= ~MKGUI_CHECKED; } }
	fl = find_widget(ctx, ED_PROP_FL_REGBOT);
	if(fl) { if(w->flags & MKGUI_REGION_BOTTOM) { fl->flags |= MKGUI_CHECKED; } else { fl->flags &= ~MKGUI_CHECKED; } }
	fl = find_widget(ctx, ED_PROP_FL_REGLEFT);
	if(fl) { if(w->flags & MKGUI_REGION_LEFT) { fl->flags |= MKGUI_CHECKED; } else { fl->flags &= ~MKGUI_CHECKED; } }
	fl = find_widget(ctx, ED_PROP_FL_REGRIGHT);
	if(fl) { if(w->flags & MKGUI_REGION_RIGHT) { fl->flags |= MKGUI_CHECKED; } else { fl->flags &= ~MKGUI_CHECKED; } }

	uint32_t is_menuitem = (w->type == MKGUI_MENUITEM);
	uint32_t has_check = (w->type == MKGUI_CHECKBOX || w->type == MKGUI_RADIO || is_menuitem);
	uint32_t in_split = 0;
	{
		int32_t pi = ed_find_widget(w->parent_id);
		if(pi >= 0) {
			uint32_t pt = ed.widgets[pi].type;
			in_split = (pt == MKGUI_HSPLIT || pt == MKGUI_VSPLIT);
		}
	}

	fl = find_widget(ctx, ED_PROP_FL_CHECKED);
	if(fl) { if(has_check) { fl->flags &= ~MKGUI_HIDDEN; } else { fl->flags |= MKGUI_HIDDEN; } }
	fl = find_widget(ctx, ED_PROP_FL_SEPARATOR);
	if(fl) { if(is_menuitem) { fl->flags &= ~MKGUI_HIDDEN; } else { fl->flags |= MKGUI_HIDDEN; } }
	fl = find_widget(ctx, ED_PROP_FL_MENUCHECK);
	if(fl) { if(is_menuitem) { fl->flags &= ~MKGUI_HIDDEN; } else { fl->flags |= MKGUI_HIDDEN; } }
	fl = find_widget(ctx, ED_PROP_FL_MENURADIO);
	if(fl) { if(is_menuitem) { fl->flags &= ~MKGUI_HIDDEN; } else { fl->flags |= MKGUI_HIDDEN; } }
	fl = find_widget(ctx, ED_PROP_FL_REGTOP);
	if(fl) { if(in_split) { fl->flags &= ~MKGUI_HIDDEN; } else { fl->flags |= MKGUI_HIDDEN; } }
	fl = find_widget(ctx, ED_PROP_FL_REGBOT);
	if(fl) { if(in_split) { fl->flags &= ~MKGUI_HIDDEN; } else { fl->flags |= MKGUI_HIDDEN; } }
	fl = find_widget(ctx, ED_PROP_FL_REGLEFT);
	if(fl) { if(in_split) { fl->flags &= ~MKGUI_HIDDEN; } else { fl->flags |= MKGUI_HIDDEN; } }
	fl = find_widget(ctx, ED_PROP_FL_REGRIGHT);
	if(fl) { if(in_split) { fl->flags &= ~MKGUI_HIDDEN; } else { fl->flags |= MKGUI_HIDDEN; } }

	ed_sync_parent_dropdown(ctx);

	uint32_t show_btns = (w->type == MKGUI_TABS || w->type == MKGUI_MENU || w->type == MKGUI_MENUITEM);
	struct mkgui_widget *btn;
	btn = find_widget(ctx, ED_PROP_BTN_HBOX);
	if(btn) { if(show_btns) { btn->flags &= ~MKGUI_HIDDEN; } else { btn->flags |= MKGUI_HIDDEN; } }
	btn = find_widget(ctx, ED_PROP_ADD_TAB);
	if(btn) { if(w->type == MKGUI_TABS) { btn->flags &= ~MKGUI_HIDDEN; } else { btn->flags |= MKGUI_HIDDEN; } }
	btn = find_widget(ctx, ED_PROP_REM_TAB);
	if(btn) { if(w->type == MKGUI_TABS) { btn->flags &= ~MKGUI_HIDDEN; } else { btn->flags |= MKGUI_HIDDEN; } }
	btn = find_widget(ctx, ED_PROP_ADD_ITEM);
	if(btn) { if(w->type == MKGUI_MENU || w->type == MKGUI_MENUITEM) { btn->flags &= ~MKGUI_HIDDEN; } else { btn->flags |= MKGUI_HIDDEN; } }
	btn = find_widget(ctx, ED_PROP_REM_ITEM);
	if(btn) { if(w->type == MKGUI_MENU || w->type == MKGUI_MENUITEM) { btn->flags &= ~MKGUI_HIDDEN; } else { btn->flags |= MKGUI_HIDDEN; } }

	ed_sync_menu_tree(ctx);

	dirty_all(ctx);
}

// [=]===^=[ ed_read_props ]======================================[=]
static void ed_read_props(struct mkgui_ctx *ctx) {
	if(ed.selected < 0 || (uint32_t)ed.selected >= ed.widget_count) {
		return;
	}
	struct ed_widget *w = &ed.widgets[ed.selected];

	const char *id_str = mkgui_input_get(ctx, ED_PROP_ID_INP);
	if(id_str && id_str[0]) {
		size_t slen = strlen(id_str);
		if(slen >= sizeof(w->id_name)) {
			slen = sizeof(w->id_name) - 1;
		}
		memcpy(w->id_name, id_str, slen);
		w->id_name[slen] = '\0';
	}

	const char *lbl_str = mkgui_input_get(ctx, ED_PROP_LABEL_INP);
	if(lbl_str) {
		size_t slen = strlen(lbl_str);
		if(slen >= MKGUI_MAX_TEXT) {
			slen = MKGUI_MAX_TEXT - 1;
		}
		memcpy(w->label, lbl_str, slen);
		w->label[slen] = '\0';
	}

	const char *icon_str = mkgui_input_get(ctx, ED_PROP_ICON_INP);
	if(icon_str) {
		size_t slen = strlen(icon_str);
		if(slen >= MKGUI_ICON_NAME_LEN) {
			slen = MKGUI_ICON_NAME_LEN - 1;
		}
		memcpy(w->icon, icon_str, slen);
		w->icon[slen] = '\0';
	}

	w->x = mkgui_spinbox_get(ctx, ED_PROP_X_SPN);
	w->y = mkgui_spinbox_get(ctx, ED_PROP_Y_SPN);
	w->w = mkgui_spinbox_get(ctx, ED_PROP_W_SPN);
	w->h = mkgui_spinbox_get(ctx, ED_PROP_H_SPN);
	w->tab_order = (uint32_t)mkgui_spinbox_get(ctx, ED_PROP_TAB_SPN);

	w->flags = 0;
	if(mkgui_checkbox_get(ctx, ED_PROP_FL_LEFT))      { w->flags |= MKGUI_ANCHOR_LEFT; }
	if(mkgui_checkbox_get(ctx, ED_PROP_FL_TOP))        { w->flags |= MKGUI_ANCHOR_TOP; }
	if(mkgui_checkbox_get(ctx, ED_PROP_FL_RIGHT))      { w->flags |= MKGUI_ANCHOR_RIGHT; }
	if(mkgui_checkbox_get(ctx, ED_PROP_FL_BOTTOM))     { w->flags |= MKGUI_ANCHOR_BOTTOM; }
	if(mkgui_checkbox_get(ctx, ED_PROP_FL_VIRTUAL))    { w->flags |= MKGUI_VIRTUAL; }
	if(mkgui_checkbox_get(ctx, ED_PROP_FL_HIDDEN))     { w->flags |= MKGUI_HIDDEN; }
	if(mkgui_checkbox_get(ctx, ED_PROP_FL_DISABLED))   { w->flags |= MKGUI_DISABLED; }
	if(mkgui_checkbox_get(ctx, ED_PROP_FL_CHECKED))    { w->flags |= MKGUI_CHECKED; }
	if(mkgui_checkbox_get(ctx, ED_PROP_FL_SEPARATOR))  { w->flags |= MKGUI_SEPARATOR; }
	if(mkgui_checkbox_get(ctx, ED_PROP_FL_MENUCHECK)) { w->flags |= MKGUI_MENU_CHECK; }
	if(mkgui_checkbox_get(ctx, ED_PROP_FL_MENURADIO)) { w->flags |= MKGUI_MENU_RADIO; }
	if(mkgui_checkbox_get(ctx, ED_PROP_FL_REGTOP))    { w->flags |= MKGUI_REGION_TOP; }
	if(mkgui_checkbox_get(ctx, ED_PROP_FL_REGBOT))    { w->flags |= MKGUI_REGION_BOTTOM; }
	if(mkgui_checkbox_get(ctx, ED_PROP_FL_REGLEFT))   { w->flags |= MKGUI_REGION_LEFT; }
	if(mkgui_checkbox_get(ctx, ED_PROP_FL_REGRIGHT))   { w->flags |= MKGUI_REGION_RIGHT; }

	dirty_all(ctx);
}

// ---------------------------------------------------------------------------
// Tab / menu management
// ---------------------------------------------------------------------------

// [=]===^=[ ed_add_tab_to_tabs ]==================================[=]
static void ed_add_tab_to_tabs(struct mkgui_ctx *ctx) {
	if(ed.selected < 0 || (uint32_t)ed.selected >= ed.widget_count) {
		return;
	}
	struct ed_widget *tabs_w = &ed.widgets[ed.selected];
	if(tabs_w->type != MKGUI_TABS || ed.widget_count >= ED_MAX_WIDGETS) {
		return;
	}

	ed_push_undo();

	uint32_t tabs_id = tabs_w->id;
	uint32_t tab_num = 0;
	for(uint32_t i = 0; i < ed.widget_count; ++i) {
		if(ed.widgets[i].type == MKGUI_TAB && ed.widgets[i].parent_id == tabs_id) {
			++tab_num;
		}
	}

	uint32_t pos = ed_insert_child_after(tabs_id);
	struct ed_widget *tab = &ed.widgets[pos];
	tab->type = MKGUI_TAB;
	tab->id = ed.next_id++;
	tab->parent_id = tabs_id;
	snprintf(tab->label, sizeof(tab->label), "Tab %u", tab_num + 1);
	tab->tab_order = pos;
	ed_gen_id_name(tab);

	ed_set_active_tab(tabs_id, tab->id);
	ed.selected = ed_find_widget(tabs_id);
	ed_sync_tree(ctx);
	ed_sync_props(ctx);
}

// [=]===^=[ ed_remove_tab_from_tabs ]=============================[=]
static void ed_remove_tab_from_tabs(struct mkgui_ctx *ctx) {
	if(ed.selected < 0 || (uint32_t)ed.selected >= ed.widget_count) {
		return;
	}
	struct ed_widget *tabs_w = &ed.widgets[ed.selected];
	if(tabs_w->type != MKGUI_TABS) {
		return;
	}

	uint32_t active = ed_get_active_tab(tabs_w->id);
	if(!active) {
		return;
	}

	uint32_t tab_count = 0;
	for(uint32_t i = 0; i < ed.widget_count; ++i) {
		if(ed.widgets[i].type == MKGUI_TAB && ed.widgets[i].parent_id == tabs_w->id) {
			++tab_count;
		}
	}
	if(tab_count <= 1) {
		return;
	}

	ed_push_undo();

	ed_delete_widget_tree(active);

	uint32_t new_active = 0;
	for(uint32_t i = 0; i < ed.widget_count; ++i) {
		if(ed.widgets[i].type == MKGUI_TAB && ed.widgets[i].parent_id == tabs_w->id) {
			new_active = ed.widgets[i].id;
			break;
		}
	}
	ed_set_active_tab(tabs_w->id, new_active);

	ed.selected = ed_find_widget(tabs_w->id);
	ed_sync_tree(ctx);
	ed_sync_props(ctx);
}

// [=]===^=[ ed_add_menu_item ]====================================[=]
static void ed_add_menu_item(struct mkgui_ctx *ctx) {
	if(ed.selected < 0 || (uint32_t)ed.selected >= ed.widget_count) {
		return;
	}
	struct ed_widget *parent_w = &ed.widgets[ed.selected];
	if((parent_w->type != MKGUI_MENU && parent_w->type != MKGUI_MENUITEM) || ed.widget_count >= ED_MAX_WIDGETS) {
		return;
	}

	ed_push_undo();

	uint32_t parent_id = parent_w->id;
	uint32_t pos = ed_insert_child_after(parent_id);
	struct ed_widget *item = &ed.widgets[pos];
	item->type = MKGUI_MENUITEM;
	item->id = ed.next_id++;
	item->parent_id = parent_id;
	snprintf(item->label, sizeof(item->label), "Item");
	item->tab_order = pos;
	ed_gen_id_name(item);

	ed.selected = ed_find_widget(parent_id);
	ed_sync_tree(ctx);
	ed_sync_props(ctx);
}

// [=]===^=[ ed_remove_menu_item ]=================================[=]
static void ed_remove_menu_item(struct mkgui_ctx *ctx) {
	if(ed.selected < 0 || (uint32_t)ed.selected >= ed.widget_count) {
		return;
	}
	struct ed_widget *sel = &ed.widgets[ed.selected];
	if(sel->type != MKGUI_MENU && sel->type != MKGUI_MENUITEM) {
		return;
	}

	if(sel->type == MKGUI_MENUITEM) {
		ed_push_undo();
		uint32_t parent_id = sel->parent_id;
		ed_delete_widget_tree(sel->id);
		ed.selected = ed_find_widget(parent_id);
		ed_sync_tree(ctx);
		ed_sync_props(ctx);
		return;
	}

	int32_t last_item = -1;
	for(uint32_t i = 0; i < ed.widget_count; ++i) {
		if(ed.widgets[i].type == MKGUI_MENUITEM && ed.widgets[i].parent_id == sel->id) {
			last_item = (int32_t)i;
		}
	}
	if(last_item < 0) {
		return;
	}

	ed_push_undo();

	uint32_t del_id = ed.widgets[last_item].id;
	ed_delete_widget_tree(del_id);

	ed.selected = ed_find_widget(sel->id);
	ed_sync_tree(ctx);
	ed_sync_props(ctx);
}

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------

// [=]===^=[ ed_generate_code ]===================================[=]
static void ed_generate_code(void) {
	FILE *fh = fopen("gui_ids.h", "w");
	FILE *fc = fopen("gui_layout.c", "w");
	if(!fh || !fc) {
		if(fh) {
			fclose(fh);
		}
		if(fc) {
			fclose(fc);
		}
		return;
	}

	fprintf(fh, "// Generated by mkgui-editor -- do not edit by hand\n");
	fprintf(fh, "#ifndef GUI_IDS_H\n");
	fprintf(fh, "#define GUI_IDS_H\n\n");
	fprintf(fh, "enum {\n");
	for(uint32_t i = 0; i < ed.widget_count; ++i) {
		fprintf(fh, "\t%s = %u,\n", ed.widgets[i].id_name, ed.widgets[i].id);
	}
	fprintf(fh, "};\n\n");
	fprintf(fh, "#endif\n");
	fclose(fh);

	fprintf(fc, "// Generated by mkgui-editor -- do not edit by hand\n\n");
	fprintf(fc, "#include \"gui_ids.h\"\n\n");
	fprintf(fc, "static struct mkgui_widget gui_widgets[] = {\n");
	for(uint32_t i = 0; i < ed.widget_count; ++i) {
		struct ed_widget *w = &ed.widgets[i];
		int32_t lx, ly, lw, lh;
		ed_convert_to_layout(i, &lx, &ly, &lw, &lh);
		fprintf(fc, "\t{ %u, %s, \"%s\", \"%s\", %u, %d, %d, %d, %d, 0x%X },\n",
			w->type, w->id_name, w->label, w->icon, w->parent_id,
			lx, ly, lw, lh, w->flags);
	}
	fprintf(fc, "};\n\n");
	fprintf(fc, "static uint32_t gui_widget_count = sizeof(gui_widgets) / sizeof(gui_widgets[0]);\n");
	fclose(fc);

	printf("Generated gui_ids.h and gui_layout.c (%u widgets)\n", ed.widget_count);
}

// ---------------------------------------------------------------------------
// Test GUI
// ---------------------------------------------------------------------------

// [=]===^=[ ed_test_gui ]========================================[=]
static void ed_test_gui(void) {
	if(ed.widget_count == 0) {
		return;
	}

	struct mkgui_widget test_widgets[ED_MAX_WIDGETS];
	for(uint32_t i = 0; i < ed.widget_count; ++i) {
		struct ed_widget *ew = &ed.widgets[i];
		struct mkgui_widget *tw = &test_widgets[i];
		tw->type = ew->type;
		tw->id = ew->id;
		size_t slen = strlen(ew->label);
		if(slen >= MKGUI_MAX_TEXT) {
			slen = MKGUI_MAX_TEXT - 1;
		}
		memcpy(tw->label, ew->label, slen);
		tw->label[slen] = '\0';
		tw->parent_id = ew->parent_id;
		memcpy(tw->icon, ew->icon, MKGUI_ICON_NAME_LEN);
		ed_convert_to_layout(i, &tw->x, &tw->y, &tw->w, &tw->h);
		tw->flags = ew->flags;
	}

	struct mkgui_ctx *test = mkgui_create(test_widgets, ed.widget_count);
	if(!test) {
		return;
	}


	struct mkgui_event ev;
	uint32_t running = 1;
	while(running) {
		while(mkgui_poll(test, &ev)) {
			if(ev.type == MKGUI_EVENT_CLOSE) {
				running = 0;
			}
		}
		mkgui_sleep_ms(16);
	}

	mkgui_destroy(test);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

#define ED_PROP_FORM_H   (6 * 24 + 5 * MKGUI_BOX_GAP)
#define ED_PROP_FL_H     (4 * 20 + 3 * MKGUI_BOX_GAP)
#define ED_PROP_GROUP_H  (ED_PROP_FORM_H + 22 + 22 + 20 + ED_PROP_FL_H + 22 + 200 + 6 * MKGUI_BOX_GAP + 36)

// [=]===^=[ main ]==============================================[=]
int main(void) {
	memset(&ed, 0, sizeof(ed));
	ed.canvas_w = ED_CANVAS_DEF_W;
	ed.canvas_h = ED_CANVAS_DEF_H;
	ed.grid_size = ED_GRID_DEFAULT;
	ed.selected = -1;
	ed.next_id = 1;

	ed_add_widget(MKGUI_WINDOW, 0, 0);
	ed.undo_pos = 0;
	ed.undo_count = 0;

	uint32_t widget_pal_count = ED_WIDGET_COUNT;
	uint32_t ctn_pal_count = ED_CONTAINER_COUNT;

	struct mkgui_widget widgets[] = {
		{ MKGUI_WINDOW,   ED_WINDOW,      "mkgui editor",    "", 0,          0, 0, 1280, 800, 0 },

		{ MKGUI_MENU,     ED_MENU,        "",                 "", ED_WINDOW,  0, 0, 0, MKGUI_MENU_HEIGHT, MKGUI_ANCHOR_LEFT | MKGUI_ANCHOR_TOP | MKGUI_ANCHOR_RIGHT },
		{ MKGUI_MENUITEM, ED_FILE_MENU,   "File",             "", ED_MENU,    0, 0, 0, 0, 0 },
		{ MKGUI_MENUITEM, ED_EDIT_MENU,   "Edit",             "", ED_MENU,    0, 0, 0, 0, 0 },
		{ MKGUI_MENUITEM, ED_MI_NEW,      "New",              "document-new",  ED_FILE_MENU, 0, 0, 0, 0, 0 },
		{ MKGUI_MENUITEM, ED_MI_OPEN,     "Open",             "document-open", ED_FILE_MENU, 0, 0, 0, 0, 0 },
		{ MKGUI_MENUITEM, ED_MI_SAVE,     "Save",             "document-save", ED_FILE_MENU, 0, 0, 0, 0, 0 },
		{ MKGUI_MENUITEM, ED_MI_GENERATE, "Generate Code",    "", ED_FILE_MENU, 0, 0, 0, 0, MKGUI_SEPARATOR },
		{ MKGUI_MENUITEM, ED_MI_EXIT,     "Exit",             "application-exit", ED_FILE_MENU, 0, 0, 0, 0, MKGUI_SEPARATOR },
		{ MKGUI_MENUITEM, ED_MI_UNDO,     "Undo",             "edit-undo", ED_EDIT_MENU, 0, 0, 0, 0, 0 },
		{ MKGUI_MENUITEM, ED_MI_REDO,     "Redo",             "edit-redo", ED_EDIT_MENU, 0, 0, 0, 0, 0 },
		{ MKGUI_MENUITEM, ED_MI_DELETE,   "Delete",           "edit-delete", ED_EDIT_MENU, 0, 0, 0, 0, MKGUI_SEPARATOR },

		{ MKGUI_TOOLBAR,  ED_TOOLBAR,     "",                 "", ED_WINDOW,  0, MKGUI_MENU_HEIGHT, 0, MKGUI_TOOLBAR_HEIGHT, MKGUI_ANCHOR_LEFT | MKGUI_ANCHOR_TOP | MKGUI_ANCHOR_RIGHT },
		{ MKGUI_BUTTON,   ED_TB_NEW,      "New",              "document-new",  ED_TOOLBAR, 0, 0, 0, 0, 0 },
		{ MKGUI_BUTTON,   ED_TB_OPEN,     "Open",             "document-open", ED_TOOLBAR, 0, 0, 0, 0, MKGUI_TOOLBAR_SEP },
		{ MKGUI_BUTTON,   ED_TB_SAVE,     "Save",             "document-save", ED_TOOLBAR, 0, 0, 0, 0, 0 },
		{ MKGUI_BUTTON,   ED_TB_GEN,      "Gen",              "", ED_TOOLBAR, 0, 0, 0, 0, MKGUI_TOOLBAR_SEP },
		{ MKGUI_BUTTON,   ED_TB_TEST,     "Test",             "", ED_TOOLBAR, 0, 0, 0, 0, 0 },
		{ MKGUI_BUTTON,   ED_TB_UNDO,     "Undo",             "edit-undo", ED_TOOLBAR, 0, 0, 0, 0, MKGUI_TOOLBAR_SEP },
		{ MKGUI_BUTTON,   ED_TB_REDO,     "Redo",             "edit-redo", ED_TOOLBAR, 0, 0, 0, 0, 0 },

		{ MKGUI_VSPLIT, ED_SPLIT_MAIN, "",              "", ED_WINDOW,  0, ED_TOP_H, 0, ED_BOT_H, MKGUI_ANCHOR_LEFT | MKGUI_ANCHOR_TOP | MKGUI_ANCHOR_RIGHT | MKGUI_ANCHOR_BOTTOM },
		{ MKGUI_TREEVIEW, ED_TREE,        "",                 "", ED_SPLIT_MAIN, 0, 0, 0, 0, MKGUI_REGION_LEFT },
		{ MKGUI_VSPLIT, ED_SPLIT_RIGHT, "",              "", ED_SPLIT_MAIN, 0, 0, 0, 0, MKGUI_REGION_RIGHT },
		{ MKGUI_LABEL,    ED_CANVAS_LBL,  "",                 "", ED_SPLIT_RIGHT, 0, 0, 0, 0, MKGUI_REGION_LEFT },
		{ MKGUI_VBOX,     ED_RIGHT_PANEL, "",                 "", ED_SPLIT_RIGHT, 0, 0, 0, 0, MKGUI_REGION_RIGHT | MKGUI_SCROLL },

		{ MKGUI_GROUP,    ED_PAL_GROUP,   "Widgets",          "", ED_RIGHT_PANEL, 0, 0, 0, ED_PALETTE_H, 0 },
		{ MKGUI_HBOX,     ED_PAL_HBOX,   "",                 "", ED_PAL_GROUP,   0, 0, 0, 0, MKGUI_ANCHOR_LEFT | MKGUI_ANCHOR_TOP | MKGUI_ANCHOR_RIGHT | MKGUI_ANCHOR_BOTTOM },
		{ MKGUI_VBOX,     ED_PAL_COL0,   "",                 "", ED_PAL_HBOX,    0, 0, 0, 0, 0 },
		{ MKGUI_VBOX,     ED_PAL_COL1,   "",                 "", ED_PAL_HBOX,    0, 0, 0, 0, 0 },

		{ MKGUI_GROUP,    ED_CTN_GROUP,   "Containers",       "", ED_RIGHT_PANEL, 0, 0, 0, ED_CTN_H, 0 },
		{ MKGUI_HBOX,     ED_CTN_HBOX,   "",                 "", ED_CTN_GROUP,   0, 0, 0, 0, MKGUI_ANCHOR_LEFT | MKGUI_ANCHOR_TOP | MKGUI_ANCHOR_RIGHT | MKGUI_ANCHOR_BOTTOM },
		{ MKGUI_VBOX,     ED_CTN_COL0,   "",                 "", ED_CTN_HBOX,    0, 0, 0, 0, 0 },
		{ MKGUI_VBOX,     ED_CTN_COL1,   "",                 "", ED_CTN_HBOX,    0, 0, 0, 0, 0 },

		/* Palette buttons generated below */

		/* Properties section */
		{ MKGUI_GROUP,    ED_PROP_GROUP,     "Properties",      "", ED_RIGHT_PANEL, 0, 0, 0, ED_PROP_GROUP_H, 0 },
		{ MKGUI_VBOX,     ED_PROP_VBOX,      "",                "", ED_PROP_GROUP, 0, 0, 0, 0, MKGUI_ANCHOR_LEFT | MKGUI_ANCHOR_TOP | MKGUI_ANCHOR_RIGHT | MKGUI_ANCHOR_BOTTOM },

		/* Form: label+control pairs */
		{ MKGUI_FORM,     ED_PROP_FORM,      "",                "", ED_PROP_VBOX, 0, 0, 0, ED_PROP_FORM_H, 0 },
		{ MKGUI_LABEL,    ED_PROP_TYPE_LBL,  "Type:",           "", ED_PROP_FORM, 0, 0, 0, 0, 0 },
		{ MKGUI_LABEL,    ED_PROP_TYPE_VAL,  "(none)",          "", ED_PROP_FORM, 0, 0, 0, 0, 0 },
		{ MKGUI_LABEL,    ED_PROP_ID_LBL,    "ID:",             "", ED_PROP_FORM, 0, 0, 0, 0, 0 },
		{ MKGUI_INPUT,    ED_PROP_ID_INP,    "",                "", ED_PROP_FORM, 0, 0, 0, 0, 0 },
		{ MKGUI_LABEL,    ED_PROP_LABEL_LBL, "Label:",          "", ED_PROP_FORM, 0, 0, 0, 0, 0 },
		{ MKGUI_INPUT,    ED_PROP_LABEL_INP, "",                "", ED_PROP_FORM, 0, 0, 0, 0, 0 },
		{ MKGUI_LABEL,    ED_PROP_ICON_LBL,  "Icon:",           "", ED_PROP_FORM, 0, 0, 0, 0, 0 },
		{ MKGUI_HBOX,     ED_PROP_ICON_HBOX, "",                "", ED_PROP_FORM, 0, 0, 0, 0, 0 },
		{ MKGUI_INPUT,    ED_PROP_ICON_INP,  "",                "", ED_PROP_ICON_HBOX, 0, 0, 0, 0, 0 },
		{ MKGUI_BUTTON,   ED_PROP_ICON_BROWSE, "...",           "", ED_PROP_ICON_HBOX, 0, 0, 26, 0, 0 },
		{ MKGUI_LABEL,    ED_PROP_PARENT_LBL, "Parent:",        "", ED_PROP_FORM, 0, 0, 0, 0, 0 },
		{ MKGUI_DROPDOWN, ED_PROP_PARENT_DRP, "",               "", ED_PROP_FORM, 0, 0, 0, 0, 0 },
		{ MKGUI_LABEL,    ED_PROP_TAB_LBL,   "Tab#:",           "", ED_PROP_FORM, 0, 0, 0, 0, 0 },
		{ MKGUI_SPINBOX,  ED_PROP_TAB_SPN,   "",                "", ED_PROP_FORM, 0, 0, 0, 0, 0 },

		/* Position row: X/Y */
		{ MKGUI_HBOX,     ED_PROP_POS_HBOX,  "",                "", ED_PROP_VBOX, 0, 0, 0, 22, 0 },
		{ MKGUI_LABEL,    ED_PROP_X_LBL,     "X:",              "", ED_PROP_POS_HBOX, 0, 0, 22, 0, 0 },
		{ MKGUI_SPINBOX,  ED_PROP_X_SPN,     "",                "", ED_PROP_POS_HBOX, 0, 0, 0, 0, 0 },
		{ MKGUI_LABEL,    ED_PROP_Y_LBL,     "Y:",              "", ED_PROP_POS_HBOX, 0, 0, 22, 0, 0 },
		{ MKGUI_SPINBOX,  ED_PROP_Y_SPN,     "",                "", ED_PROP_POS_HBOX, 0, 0, 0, 0, 0 },

		/* Size row: W/H */
		{ MKGUI_HBOX,     ED_PROP_SIZE_HBOX, "",                "", ED_PROP_VBOX, 0, 0, 0, 22, 0 },
		{ MKGUI_LABEL,    ED_PROP_W_LBL,     "W:",              "", ED_PROP_SIZE_HBOX, 0, 0, 22, 0, 0 },
		{ MKGUI_SPINBOX,  ED_PROP_W_SPN,     "",                "", ED_PROP_SIZE_HBOX, 0, 0, 0, 0, 0 },
		{ MKGUI_LABEL,    ED_PROP_H_LBL,     "H:",              "", ED_PROP_SIZE_HBOX, 0, 0, 22, 0, 0 },
		{ MKGUI_SPINBOX,  ED_PROP_H_SPN,     "",                "", ED_PROP_SIZE_HBOX, 0, 0, 0, 0, 0 },

		/* Flags */
		{ MKGUI_LABEL,    ED_PROP_FLAGS_LBL, "Anchors/Flags:",  "", ED_PROP_VBOX, 0, 0, 0, 20, 0 },
		{ MKGUI_HBOX,     ED_PROP_FL_HBOX,   "",                "", ED_PROP_VBOX, 0, 0, 0, ED_PROP_FL_H, 0 },
		{ MKGUI_VBOX,     ED_PROP_FL_COL0,   "",                "", ED_PROP_FL_HBOX, 0, 0, 0, 0, 0 },
		{ MKGUI_VBOX,     ED_PROP_FL_COL1,   "",                "", ED_PROP_FL_HBOX, 0, 0, 0, 0, 0 },
		{ MKGUI_VBOX,     ED_PROP_FL_COL2,   "",                "", ED_PROP_FL_HBOX, 0, 0, 0, 0, 0 },
		{ MKGUI_VBOX,     ED_PROP_FL_COL3,   "",                "", ED_PROP_FL_HBOX, 0, 0, 0, 0, 0 },
		{ MKGUI_CHECKBOX, ED_PROP_FL_LEFT,    "Left",           "", ED_PROP_FL_COL0, 0, 0, 0, 20, 0 },
		{ MKGUI_CHECKBOX, ED_PROP_FL_REGTOP,  "RgnTop",         "", ED_PROP_FL_COL0, 0, 0, 0, 20, 0 },
		{ MKGUI_CHECKBOX, ED_PROP_FL_VIRTUAL, "Virtual",        "", ED_PROP_FL_COL0, 0, 0, 0, 20, 0 },
		{ MKGUI_CHECKBOX, ED_PROP_FL_CHECKED, "Checked",        "", ED_PROP_FL_COL0, 0, 0, 0, 20, 0 },
		{ MKGUI_CHECKBOX, ED_PROP_FL_TOP,     "Top",            "", ED_PROP_FL_COL1, 0, 0, 0, 20, 0 },
		{ MKGUI_CHECKBOX, ED_PROP_FL_REGBOT,  "RgnBot",         "", ED_PROP_FL_COL1, 0, 0, 0, 20, 0 },
		{ MKGUI_CHECKBOX, ED_PROP_FL_HIDDEN,  "Hidden",         "", ED_PROP_FL_COL1, 0, 0, 0, 20, 0 },
		{ MKGUI_CHECKBOX, ED_PROP_FL_SEPARATOR,"Sep",            "", ED_PROP_FL_COL1, 0, 0, 0, 20, 0 },
		{ MKGUI_CHECKBOX, ED_PROP_FL_RIGHT,   "Right",          "", ED_PROP_FL_COL2, 0, 0, 0, 20, 0 },
		{ MKGUI_CHECKBOX, ED_PROP_FL_REGLEFT, "RgnLeft",        "", ED_PROP_FL_COL2, 0, 0, 0, 20, 0 },
		{ MKGUI_CHECKBOX, ED_PROP_FL_DISABLED,"Disabled",       "", ED_PROP_FL_COL2, 0, 0, 0, 20, 0 },
		{ MKGUI_CHECKBOX, ED_PROP_FL_MENUCHECK,"MChk",          "", ED_PROP_FL_COL2, 0, 0, 0, 20, 0 },
		{ MKGUI_CHECKBOX, ED_PROP_FL_BOTTOM,  "Bottom",         "", ED_PROP_FL_COL3, 0, 0, 0, 20, 0 },
		{ MKGUI_CHECKBOX, ED_PROP_FL_REGRIGHT,"RgnRight",       "", ED_PROP_FL_COL3, 0, 0, 0, 20, 0 },
		{ MKGUI_CHECKBOX, ED_PROP_FL_MENURADIO,"MRad",          "", ED_PROP_FL_COL3, 0, 0, 0, 20, 0 },

		/* Add/Remove buttons */
		{ MKGUI_HBOX,     ED_PROP_BTN_HBOX,  "",                "", ED_PROP_VBOX, 0, 0, 0, 22, MKGUI_HIDDEN },
		{ MKGUI_BUTTON,   ED_PROP_ADD_TAB,   "Add Tab",         "", ED_PROP_BTN_HBOX, 0, 0, 0, 0, MKGUI_HIDDEN },
		{ MKGUI_BUTTON,   ED_PROP_REM_TAB,   "Remove Tab",      "", ED_PROP_BTN_HBOX, 0, 0, 0, 0, MKGUI_HIDDEN },
		{ MKGUI_BUTTON,   ED_PROP_ADD_ITEM,  "Add Item",        "", ED_PROP_BTN_HBOX, 0, 0, 0, 0, MKGUI_HIDDEN },
		{ MKGUI_BUTTON,   ED_PROP_REM_ITEM,  "Remove Item",     "", ED_PROP_BTN_HBOX, 0, 0, 0, 0, MKGUI_HIDDEN },

		/* Menu tree */
		{ MKGUI_TREEVIEW, ED_MENU_TREE,      "",                "", ED_PROP_VBOX, 0, 0, 0, 200, MKGUI_HIDDEN },

		{ MKGUI_STATUSBAR, ED_STATUSBAR,   "",                 "", ED_WINDOW,  0, 0, 0, ED_BOT_H, MKGUI_ANCHOR_LEFT | MKGUI_ANCHOR_BOTTOM | MKGUI_ANCHOR_RIGHT },
	};

	uint32_t base_count = sizeof(widgets) / sizeof(widgets[0]);

	struct mkgui_widget all_widgets[256];
	memcpy(all_widgets, widgets, base_count * sizeof(struct mkgui_widget));
	uint32_t total = base_count;

	for(uint32_t i = 0; i < widget_pal_count && total < 256; ++i) {
		struct mkgui_widget *pw = &all_widgets[total++];
		pw->type = MKGUI_BUTTON;
		pw->id = ED_PAL_FIRST + i;
		size_t slen = strlen(ed_widgets[i].name);
		if(slen >= MKGUI_MAX_TEXT) {
			slen = MKGUI_MAX_TEXT - 1;
		}
		memcpy(pw->label, ed_widgets[i].name, slen);
		pw->label[slen] = '\0';
		pw->icon[0] = '\0';
		pw->parent_id = (i % 2 == 0) ? ED_PAL_COL0 : ED_PAL_COL1;
		pw->x = 0;
		pw->y = 0;
		pw->w = 0;
		pw->h = 22;
		pw->flags = 0;
	}

	for(uint32_t i = 0; i < ctn_pal_count && total < 256; ++i) {
		struct mkgui_widget *pw = &all_widgets[total++];
		pw->type = MKGUI_BUTTON;
		pw->id = ED_CTN_FIRST + i;
		size_t slen = strlen(ed_containers[i].name);
		if(slen >= MKGUI_MAX_TEXT) {
			slen = MKGUI_MAX_TEXT - 1;
		}
		memcpy(pw->label, ed_containers[i].name, slen);
		pw->label[slen] = '\0';
		pw->icon[0] = '\0';
		pw->parent_id = (i % 2 == 0) ? ED_CTN_COL0 : ED_CTN_COL1;
		pw->x = 0;
		pw->y = 0;
		pw->w = 0;
		pw->h = 22;
		pw->flags = 0;
	}

	struct mkgui_ctx *ctx = mkgui_create(all_widgets, total);
	if(!ctx) {
		return 1;
	}


	struct mkgui_split_data *sd_main = find_split_data(ctx, ED_SPLIT_MAIN);
	if(sd_main) {
		sd_main->ratio = (float)ED_LEFT_W / 1280.0f;
	}
	struct mkgui_split_data *sd_right = find_split_data(ctx, ED_SPLIT_RIGHT);
	if(sd_right) {
		sd_right->ratio = 1.0f - (float)ED_RIGHT_W / (1280.0f - ED_LEFT_W - MKGUI_SPLIT_THICK);
	}

	ctx->render_cb = ed_render_canvas;
	ctx->render_cb_data = NULL;

	int32_t sb_widths[] = { -1, 120 };
	mkgui_statusbar_setup(ctx, ED_STATUSBAR, 2, sb_widths);
	mkgui_statusbar_set(ctx, ED_STATUSBAR, 0, "Ready");
	mkgui_statusbar_set(ctx, ED_STATUSBAR, 1, "Grid: 8px");

	mkgui_spinbox_setup(ctx, ED_PROP_X_SPN, -9999, 9999, 0, 1);
	mkgui_spinbox_setup(ctx, ED_PROP_Y_SPN, -9999, 9999, 0, 1);
	mkgui_spinbox_setup(ctx, ED_PROP_W_SPN, 0, 9999, 0, 1);
	mkgui_spinbox_setup(ctx, ED_PROP_H_SPN, 0, 9999, 0, 1);
	mkgui_spinbox_setup(ctx, ED_PROP_TAB_SPN, 0, 999, 0, 1);

	ed_sync_tree(ctx);
	ed_sync_props(ctx);

	struct mkgui_event ev;
	uint32_t running = 1;
	uint32_t prev_press = 0;

	while(running) {
		while(mkgui_poll(ctx, &ev)) {
			switch(ev.type) {
				case MKGUI_EVENT_CLOSE: {
					running = 0;
				} break;

				case MKGUI_EVENT_CLICK: {
					if(ev.id == ED_TB_NEW || ev.id == ED_MI_NEW) {
						memset(&ed, 0, sizeof(ed));
						ed.canvas_w = ED_CANVAS_DEF_W;
						ed.canvas_h = ED_CANVAS_DEF_H;
						ed.grid_size = ED_GRID_DEFAULT;
						ed.selected = -1;
						ed.next_id = 1;
						ed_add_widget(MKGUI_WINDOW, 0, 0);
						ed.undo_pos = 0;
						ed.undo_count = 0;
						ed_sync_tree(ctx);
						ed_sync_props(ctx);
						mkgui_statusbar_set(ctx, ED_STATUSBAR, 0, "New project");

					} else if(ev.id == ED_TB_GEN || ev.id == ED_MI_GENERATE) {
						ed_generate_code();
						mkgui_statusbar_set(ctx, ED_STATUSBAR, 0, "Code generated");

					} else if(ev.id == ED_TB_TEST) {
						ed_test_gui();
						dirty_all(ctx);

					} else if(ev.id == ED_TB_UNDO || ev.id == ED_MI_UNDO) {
						ed_undo();
						ed_sync_tree(ctx);
						ed_sync_props(ctx);

					} else if(ev.id == ED_TB_REDO || ev.id == ED_MI_REDO) {
						ed_redo();
						ed_sync_tree(ctx);
						ed_sync_props(ctx);

					} else if(ev.id == ED_MI_DELETE) {
						ed_delete_selected();
						ed_sync_tree(ctx);
						ed_sync_props(ctx);

					} else if(ev.id == ED_MI_EXIT) {
						running = 0;

					} else if(ev.id == ED_PROP_ICON_BROWSE) {
						char icon_name[64];
						if(mkgui_icon_browser(ctx, icon_name, sizeof(icon_name))) {
							mkgui_input_set(ctx, ED_PROP_ICON_INP, icon_name);
							if(ed.selected >= 0) {
								strncpy(ed.widgets[ed.selected].icon, icon_name, MKGUI_ICON_NAME_LEN - 1);
								ed.widgets[ed.selected].icon[MKGUI_ICON_NAME_LEN - 1] = '\0';
								ed_push_undo();
							}
						}

					} else if(ev.id == ED_PROP_ADD_TAB) {
						ed_add_tab_to_tabs(ctx);

					} else if(ev.id == ED_PROP_REM_TAB) {
						ed_remove_tab_from_tabs(ctx);

					} else if(ev.id == ED_PROP_ADD_ITEM) {
						ed_add_menu_item(ctx);

					} else if(ev.id == ED_PROP_REM_ITEM) {
						ed_remove_menu_item(ctx);

					} else {
						for(uint32_t pi = 0; pi < widget_pal_count; ++pi) {
							if(ev.id == ED_PAL_FIRST + pi) {
								ed.placement_type = ed_widgets[pi].type;
								dirty_all(ctx);
								char buf[128];
								snprintf(buf, sizeof(buf), "Place: %s", ed_widgets[pi].name);
								mkgui_statusbar_set(ctx, ED_STATUSBAR, 0, buf);
								break;
							}
						}
						for(uint32_t pi = 0; pi < ctn_pal_count; ++pi) {
							if(ev.id == ED_CTN_FIRST + pi) {
								ed.placement_type = ed_containers[pi].type;
								dirty_all(ctx);
								char buf[128];
								snprintf(buf, sizeof(buf), "Place: %s", ed_containers[pi].name);
								mkgui_statusbar_set(ctx, ED_STATUSBAR, 0, buf);
								break;
							}
						}
					}
				} break;

				case MKGUI_EVENT_MENU: {
					if(ev.id == ED_MI_EXIT) {
						running = 0;
					} else if(ev.id == ED_MI_GENERATE) {
						ed_generate_code();
						mkgui_statusbar_set(ctx, ED_STATUSBAR, 0, "Code generated");
					} else if(ev.id == ED_MI_UNDO) {
						ed_undo();
						ed_sync_tree(ctx);
						ed_sync_props(ctx);
					} else if(ev.id == ED_MI_REDO) {
						ed_redo();
						ed_sync_tree(ctx);
						ed_sync_props(ctx);
					} else if(ev.id == ED_MI_DELETE) {
						ed_delete_selected();
						ed_sync_tree(ctx);
						ed_sync_props(ctx);
					} else if(ev.id == ED_MI_NEW) {
						memset(&ed, 0, sizeof(ed));
						ed.canvas_w = ED_CANVAS_DEF_W;
						ed.canvas_h = ED_CANVAS_DEF_H;
						ed.grid_size = ED_GRID_DEFAULT;
						ed.selected = -1;
						ed.next_id = 1;
						ed_add_widget(MKGUI_WINDOW, 0, 0);
						ed.undo_pos = 0;
						ed.undo_count = 0;
						ed_sync_tree(ctx);
						ed_sync_props(ctx);
					}
				} break;

				case MKGUI_EVENT_TREEVIEW_SELECT: {
					if(ev.id == ED_TREE) {
						int32_t idx = ed_find_widget((uint32_t)ev.value);
						if(idx >= 0) {
							ed.selected = idx;
							ed_sync_props(ctx);
						}
					} else if(ev.id == ED_MENU_TREE) {
						int32_t idx = ed_find_widget((uint32_t)ev.value);
						if(idx >= 0) {
							ed.selected = idx;
							struct mkgui_treeview_data *mt = find_treeview_data(ctx, ED_MENU_TREE);
							int32_t saved_scroll = mt ? mt->scroll_y : 0;
							ed_sync_props(ctx);
							mt = find_treeview_data(ctx, ED_MENU_TREE);
							if(mt) {
								mt->scroll_y = saved_scroll;
							}
							struct mkgui_treeview_data *mtv = find_treeview_data(ctx, ED_TREE);
							if(mtv) {
								mtv->selected_node = (int32_t)ev.value;
							}
						}
					}
				} break;

				case MKGUI_EVENT_SPINBOX_CHANGED:
				case MKGUI_EVENT_INPUT_CHANGED: {
					if(ev.id >= ED_PROP_X_SPN && ev.id <= ED_PROP_TAB_SPN) {
						ed_read_props(ctx);
					}
					if(ev.id == ED_PROP_ICON_INP) {
						ed_read_props(ctx);
					}
					if(ev.id == ED_PROP_ID_INP || ev.id == ED_PROP_LABEL_INP) {
						ed_read_props(ctx);
						ed_sync_tree(ctx);
						ed_sync_menu_tree(ctx);
					}
				} break;

				case MKGUI_EVENT_CHECKBOX_CHANGED: {
					if(ev.id >= ED_PROP_FL_LEFT && ev.id <= ED_PROP_FL_REGRIGHT) {
						ed_read_props(ctx);
					}
				} break;

				case MKGUI_EVENT_DROPDOWN_CHANGED: {
					if(ev.id == ED_PROP_PARENT_DRP) {
						ed_apply_parent_dropdown(ctx);
					}
				} break;

				case MKGUI_EVENT_KEY: {
					if(ev.keysym == MKGUI_KEY_ESCAPE) {
						ed.placement_type = 0;
						mkgui_statusbar_set(ctx, ED_STATUSBAR, 0, "Ready");
						dirty_all(ctx);
					}

					if(ev.keysym == MKGUI_KEY_DELETE) {
						if(ed.selected >= 0 && (uint32_t)ed.selected < ed.widget_count && ed.widgets[ed.selected].type == MKGUI_MENUITEM) {
							ed_remove_menu_item(ctx);
						} else {
							ed_delete_selected();
							ed_sync_tree(ctx);
							ed_sync_props(ctx);
						}
					}

					if((ev.keymod & MKGUI_MOD_CONTROL) && ev.keysym == 'z') {
						ed_undo();
						ed_sync_tree(ctx);
						ed_sync_props(ctx);
					}

					if((ev.keymod & MKGUI_MOD_CONTROL) && (ev.keysym == 'Z' || ev.keysym == 'y')) {
						ed_redo();
						ed_sync_tree(ctx);
						ed_sync_props(ctx);
					}
				} break;

				default: break;
			}
		}

		int32_t ci = find_widget_idx(ctx, ED_CANVAS_LBL);
		if(ci >= 0) {
			int32_t crx = ctx->rects[ci].x;
			int32_t cry = ctx->rects[ci].y;
			int32_t crw = ctx->rects[ci].w;
			int32_t crh = ctx->rects[ci].h;

			int32_t win_x = crx + (crw - ed.canvas_w) / 2;
			int32_t win_y = cry + (crh - ed.canvas_h) / 2;

			if(ctx->press_id == ED_CANVAS_LBL && !prev_press) {
				int32_t local_x = ctx->mouse_x - win_x;
				int32_t local_y = ctx->mouse_y - win_y;

				if(ed.placement_type) {
					int32_t sx = ed_snap(local_x);
					int32_t sy = ed_snap(local_y);
					int32_t new_idx = ed_add_widget(ed.placement_type, sx, sy);
					if(new_idx >= 0) {
						uint32_t new_parent = 0;
						for(int32_t j = (int32_t)ed.widget_count - 2; j >= 0; --j) {
							struct ed_widget *c = &ed.widgets[j];
							if(c->type == MKGUI_TABS) {
								if(sx >= c->x && sx < c->x + c->w && sy >= c->y + MKGUI_TAB_HEIGHT && sy < c->y + c->h) {
									uint32_t active = ed_get_active_tab(c->id);
									if(active) {
										new_parent = active;
									}
									break;
								}

							} else if(c->type == MKGUI_HSPLIT || c->type == MKGUI_VSPLIT) {
								if(sx >= c->x && sx < c->x + c->w && sy >= c->y && sy < c->y + c->h) {
									new_parent = c->id;
									break;
								}

							} else if(c->type == MKGUI_MENU) {
								if(sx >= c->x && sx < c->x + c->w && sy >= c->y && sy < c->y + c->h) {
									new_parent = c->id;
									break;
								}
							}
						}
						if(new_parent) {
							struct ed_widget tmp = ed.widgets[new_idx];
							tmp.parent_id = new_parent;
							memmove(&ed.widgets[new_idx], &ed.widgets[new_idx + 1], (ed.widget_count - (uint32_t)new_idx - 1) * sizeof(struct ed_widget));
							--ed.widget_count;
							uint32_t pos = ed_insert_child_after(new_parent);
							ed.widgets[pos] = tmp;
							new_idx = (int32_t)pos;
						}
						ed.selected = new_idx;
						ed_sync_tree(ctx);
						ed_sync_props(ctx);
					}
					dirty_all(ctx);

				} else {
					uint32_t tab_switched = 0;
					for(uint32_t ti = 0; ti < ed.widget_count; ++ti) {
						if(ed.widgets[ti].type == MKGUI_TABS) {
							uint32_t tab_id = ed_tab_header_hit(ctx, (int32_t)ti, local_x, local_y);
							if(tab_id) {
								ed_set_active_tab(ed.widgets[ti].id, tab_id);
								ed.selected = (int32_t)ti;
								ed_sync_props(ctx);
								dirty_all(ctx);
								tab_switched = 1;
								break;
							}
						}
					}

					if(tab_switched) {

					} else {
					int32_t handle = ed_handle_hit(local_x, local_y);
					if(handle >= 0) {
						ed.resize_handle = handle;
						ed.drag_active = 2;
						ed.drag_ox = local_x;
						ed.drag_oy = local_y;
						ed.resize_start_x = ed.widgets[ed.selected].x;
						ed.resize_start_y = ed.widgets[ed.selected].y;
						ed.resize_start_w = ed.widgets[ed.selected].w;
						ed.resize_start_h = ed.widgets[ed.selected].h;

					} else {
						uint32_t cedge = ed_canvas_edge_hit(local_x, local_y);
						if(cedge) {
							ed.canvas_resize_edge = cedge;
							ed.drag_active = 3;
							ed.drag_ox = ctx->mouse_x;
							ed.drag_oy = ctx->mouse_y;
							ed.selected = -1;
							ed_sync_props(ctx);

						} else {
							int32_t hit = ed_canvas_hit(local_x, local_y);
							if(hit >= 0) {
								ed.selected = hit;
								ed.drag_active = 1;
								ed.drag_ox = local_x - ed.widgets[hit].x;
								ed.drag_oy = local_y - ed.widgets[hit].y;
								ed_sync_props(ctx);

							} else {
								ed.selected = -1;
								ed_sync_props(ctx);
							}
						}
					}
					}
					dirty_all(ctx);
				}
			}

			if(ed.drag_active && ctx->press_id == ED_CANVAS_LBL) {
				int32_t local_x = ctx->mouse_x - win_x;
				int32_t local_y = ctx->mouse_y - win_y;

				if(ed.drag_active == 1 && ed.selected >= 0) {
					int32_t new_x = ed_snap(local_x - ed.drag_ox);
					int32_t new_y = ed_snap(local_y - ed.drag_oy);
					int32_t dx = new_x - ed.widgets[ed.selected].x;
					int32_t dy = new_y - ed.widgets[ed.selected].y;
					ed.widgets[ed.selected].x = new_x;
					ed.widgets[ed.selected].y = new_y;
					uint32_t sel_id = ed.widgets[ed.selected].id;
					for(uint32_t mi = 0; mi < ed.widget_count; ++mi) {
						if((int32_t)mi != ed.selected && ed_is_descendant(mi, sel_id)) {
							ed.widgets[mi].x += dx;
							ed.widgets[mi].y += dy;
						}
					}
					ed_sync_props(ctx);
					dirty_all(ctx);

				} else if(ed.drag_active == 2 && ed.selected >= 0) {
					struct ed_widget *w = &ed.widgets[ed.selected];
					int32_t prev_x = w->x;
					int32_t prev_y = w->y;
					int32_t dx = local_x - ed.drag_ox;
					int32_t dy = local_y - ed.drag_oy;
					int32_t sx = ed.resize_start_x;
					int32_t sy = ed.resize_start_y;
					int32_t sw = ed.resize_start_w;
					int32_t sh = ed.resize_start_h;
					int32_t right = sx + sw;
					int32_t bottom = sy + sh;

					switch(ed.resize_handle) {
						case 0: {
							w->x = ed_snap(sx + dx);
							w->y = ed_snap(sy + dy);
							w->w = right - w->x;
							w->h = bottom - w->y;
						} break;

						case 1: {
							w->y = ed_snap(sy + dy);
							w->h = bottom - w->y;
						} break;

						case 2: {
							w->y = ed_snap(sy + dy);
							w->w = ed_snap(sw + dx);
							w->h = bottom - w->y;
						} break;

						case 3: {
							w->w = ed_snap(sw + dx);
						} break;

						case 4: {
							w->w = ed_snap(sw + dx);
							w->h = ed_snap(sh + dy);
						} break;

						case 5: {
							w->h = ed_snap(sh + dy);
						} break;

						case 6: {
							w->x = ed_snap(sx + dx);
							w->w = right - w->x;
							w->h = ed_snap(sh + dy);
						} break;

						case 7: {
							w->x = ed_snap(sx + dx);
							w->w = right - w->x;
						} break;

						default: break;
					}
					if(w->w < 4) {
						w->w = 4;
					}
					if(w->h < 4) {
						w->h = 4;
					}
					int32_t child_dx = w->x - prev_x;
					int32_t child_dy = w->y - prev_y;
					if(child_dx || child_dy) {
						uint32_t sel_id = w->id;
						for(uint32_t mi = 0; mi < ed.widget_count; ++mi) {
							if((int32_t)mi != ed.selected && ed_is_descendant(mi, sel_id)) {
								ed.widgets[mi].x += child_dx;
								ed.widgets[mi].y += child_dy;
							}
						}
					}
					ed_sync_props(ctx);
					dirty_all(ctx);

				} else if(ed.drag_active == 3) {
					int32_t adx = ctx->mouse_x - ed.drag_ox;
					int32_t ady = ctx->mouse_y - ed.drag_oy;

					int32_t old_cw = ed.canvas_w;
					int32_t old_ch = ed.canvas_h;

					if(ed.canvas_resize_edge & ED_EDGE_RIGHT) {
						ed.canvas_w += adx;
					}
					if(ed.canvas_resize_edge & ED_EDGE_BOTTOM) {
						ed.canvas_h += ady;
					}
					if(ed.canvas_resize_edge & ED_EDGE_LEFT) {
						ed.canvas_w -= adx;
					}
					if(ed.canvas_resize_edge & ED_EDGE_TOP) {
						ed.canvas_h -= ady;
					}
					if(ed.canvas_w < ED_CANVAS_MIN) {
						ed.canvas_w = ED_CANVAS_MIN;
					}
					if(ed.canvas_h < ED_CANVAS_MIN) {
						ed.canvas_h = ED_CANVAS_MIN;
					}

					int32_t dx = ed.canvas_w - old_cw;
					int32_t dy = ed.canvas_h - old_ch;
					if(dx != 0 || dy != 0) {
						uint32_t win_id = ed.widgets[0].id;
						ed.widgets[0].w = ed.canvas_w;
						ed.widgets[0].h = ed.canvas_h;
						for(uint32_t i = 1; i < ed.widget_count; ++i) {
							struct ed_widget *aw = &ed.widgets[i];
							if(aw->parent_id != win_id) {
								continue;
							}
							uint32_t af = aw->flags;
							if((af & MKGUI_ANCHOR_LEFT) && (af & MKGUI_ANCHOR_RIGHT)) {
								aw->w += dx;
							} else if(af & MKGUI_ANCHOR_RIGHT) {
								aw->x += dx;
							}
							if((af & MKGUI_ANCHOR_TOP) && (af & MKGUI_ANCHOR_BOTTOM)) {
								aw->h += dy;
							} else if(af & MKGUI_ANCHOR_BOTTOM) {
								aw->y += dy;
							}
						}
					}

					ed.drag_ox = ctx->mouse_x;
					ed.drag_oy = ctx->mouse_y;
					dirty_all(ctx);
				}
			}

			if(!ctx->press_id && ed.drag_active) {
				if(ed.drag_active && ed.selected >= 0) {
					ed_push_undo();
				}
				ed.drag_active = 0;
			}

			prev_press = ctx->press_id;
		}

		mkgui_sleep_ms(16);
	}

	mkgui_destroy(ctx);
	return 0;
}
