// Copyright (c) 2026, Peter Fors
// SPDX-License-Identifier: MIT
//
// Clipboard tests: the now-unbounded internal selection storage, and the X11
// INCR (incremental) transfer path for selections too large to move in a
// single X request.
//
// Same-process copy/paste short-circuits through the owner's internal buffer
// (no X round-trip), so the INCR state machine only runs between distinct X
// clients. The cross-process test forks: the parent owns a multi-megabyte
// selection and pumps its event loop (driving the owner-side INCR send), while
// the child reads it back through platform_clipboard_get_alloc (driving the
// requestor-side INCR receive) and verifies every byte. Both ends are mkgui,
// so one round-trip exercises both halves of the protocol.

#include "../mkgui.c"

#include <sys/wait.h>

// Comfortably past the 1 MB per-chunk cap, with a deliberately non-aligned
// tail so the final short chunk and the chunk-boundary paging both get hit.
#define BIG_LEN (5u * 1024u * 1024u + 12345u)

// Deterministic, NUL-free, printable payload. Regenerated by index on the
// receiving side, so any chunk-boundary or ordering bug shows up as a
// mismatch at the exact offset it occurred.
static void clip_fill_pattern(char *buf, uint32_t len) {
	for(uint32_t i = 0; i < len; ++i) {
		buf[i] = (char)(33 + (i % 94));
	}
}

// [=]===^=[ clip_test_internal_large ]============================[=]
// The owner reading its own selection takes the internal-buffer path; this
// proves that path is no longer capped at the old 4 KB MKGUI_CLIP_MAX.
static uint32_t clip_test_internal_large(void) {
	struct mkgui_widget widgets[] = {
		MKGUI_W(MKGUI_WINDOW, 1, "clip", "", 0, 64, 64, 0, 0, 0),
	};
	struct mkgui_ctx *ctx = mkgui_ctx_create();
	struct mkgui_window *win = mkgui_window_create(ctx, NULL, widgets, 1, NULL, 0, 0);
	if(!win) {
		printf("  internal: window_create failed\n");
		mkgui_ctx_destroy(ctx);
		return 1;
	}

	char *src = (char *)malloc(BIG_LEN);
	clip_fill_pattern(src, BIG_LEN);
	platform_clipboard_set(win, src, BIG_LEN);

	uint32_t got_len = 0;
	char *got = platform_clipboard_get_alloc(win, &got_len);

	uint32_t ok = got && got_len == BIG_LEN && memcmp(got, src, BIG_LEN) == 0;
	if(!ok) {
		printf("  internal: mismatch (want %u, got %u)\n", BIG_LEN, got_len);
	}

	free(got);
	free(src);
	mkgui_window_destroy(win);
	mkgui_ctx_destroy(ctx);
	return ok ? 0 : 1;
}

// [=]===^=[ clip_child_requestor ]================================[=]
// Child process: read the big selection the parent owns and verify it.
// Exit code is the failure reason (0 == success).
static void clip_child_requestor(int ready_fd) {
	char c;
	if(read(ready_fd, &c, 1) != 1) {
		_exit(10);
	}
	close(ready_fd);

	struct mkgui_widget widgets[] = {
		MKGUI_W(MKGUI_WINDOW, 1, "clip-recv", "", 0, 64, 64, 0, 0, 0),
	};
	struct mkgui_ctx *ctx = mkgui_ctx_create();
	struct mkgui_window *win = mkgui_window_create(ctx, NULL, widgets, 1, NULL, 0, 0);
	if(!win) {
		mkgui_ctx_destroy(ctx);
		_exit(11);
	}

	uint32_t got_len = 0;
	char *got = platform_clipboard_get_alloc(win, &got_len);

	int status = 0;
	if(!got) {
		status = 12;
	} else if(got_len != BIG_LEN) {
		status = 13;
	} else {
		char *ref = (char *)malloc(BIG_LEN);
		clip_fill_pattern(ref, BIG_LEN);
		if(memcmp(got, ref, BIG_LEN) != 0) {
			status = 14;
		}
		free(ref);
	}

	free(got);
	mkgui_window_destroy(win);
	mkgui_ctx_destroy(ctx);
	_exit(status);
}

// [=]===^=[ clip_test_incr_roundtrip ]============================[=]
static uint32_t clip_test_incr_roundtrip(void) {
	int ready[2];
	if(pipe(ready) != 0) {
		printf("  incr: pipe failed\n");
		return 1;
	}

	pid_t pid = fork();
	if(pid < 0) {
		printf("  incr: fork failed\n");
		close(ready[0]);
		close(ready[1]);
		return 1;
	}

	if(pid == 0) {
		close(ready[1]);
		clip_child_requestor(ready[0]);
		_exit(99);	// unreachable
	}

	close(ready[0]);

	struct mkgui_widget widgets[] = {
		MKGUI_W(MKGUI_WINDOW, 1, "clip-own", "", 0, 64, 64, 0, 0, 0),
	};
	struct mkgui_ctx *ctx = mkgui_ctx_create();
	struct mkgui_window *win = mkgui_window_create(ctx, NULL, widgets, 1, NULL, 0, 0);
	if(!win) {
		printf("  incr: parent window_create failed\n");
		close(ready[1]);
		waitpid(pid, NULL, 0);
		mkgui_ctx_destroy(ctx);
		return 1;
	}

	char *src = (char *)malloc(BIG_LEN);
	clip_fill_pattern(src, BIG_LEN);
	platform_clipboard_set(win, src, BIG_LEN);
	free(src);
	// Make the ownership visible to the child's server-side query before we
	// release it; XFlush alone only queues the request locally.
	XSync(win->plat.dpy, False);

	char go = 1;
	if(write(ready[1], &go, 1) != 1) {
		printf("  incr: ready signal failed\n");
	}
	close(ready[1]);

	// Pump the owner event loop (this is what services the requestor's
	// SelectionRequest and the property-delete pacing) until the child is
	// done. A wall-clock deadline keeps a protocol stall from hanging CI.
	uint64_t deadline = mkgui_now_ns() + 60ull * 1000000000ull;
	int status = 0;
	uint32_t timed_out = 0;
	for(;;) {
		if(waitpid(pid, &status, WNOHANG) == pid) {
			break;
		}
		if(mkgui_now_ns() > deadline) {
			timed_out = 1;
			kill(pid, SIGKILL);
			waitpid(pid, &status, 0);
			break;
		}
		platform_wait_event(win, 20ll * 1000000ll);
		struct mkgui_event ev;
		while(mkgui_window_poll(win, &ev)) {
		}
	}

	uint32_t ok = !timed_out && WIFEXITED(status) && WEXITSTATUS(status) == 0;
	if(timed_out) {
		printf("  incr: timed out waiting for child\n");
	} else if(!ok) {
		printf("  incr: child failed (exit %d)\n", WIFEXITED(status) ? WEXITSTATUS(status) : -1);
	}

	mkgui_window_destroy(win);
	mkgui_ctx_destroy(ctx);
	return ok ? 0 : 1;
}

// [=]===^=[ main ]================================================[=]
int main(void) {
	Display *probe = XOpenDisplay(NULL);
	if(!probe) {
		printf("test_clipboard: no X display, SKIP\n");
		return 0;
	}
	XCloseDisplay(probe);

	uint32_t failed = 0;
	failed |= clip_test_internal_large();
	failed |= clip_test_incr_roundtrip();

	if(failed) {
		printf("test_clipboard: FAIL\n");
		return 1;
	}
	printf("test_clipboard: all tests passed\n");
	return 0;
}
